import { appCommonStylesByTheme } from "./appCommonStyles";
import { chatComposerStylesByTheme } from "./chatComposerStyles";
import { chatMessageStylesByTheme } from "./chatMessageStyles";
import { VISUAL_THEMES, type VisualTheme, type VisualThemeId } from "../theme/visualThemes";

export function createAppLayoutStyles(theme: VisualTheme) {
  return {
  ...appCommonStylesByTheme[theme.id],
  appOverlaySafeArea: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
  },
  drawerPopupOverlayHost: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    zIndex: 300,
    elevation: 300,
  },
  drawerPopupSafeArea: {
    flex: 1,
    backgroundColor: "transparent",
  },
  llmCompletionNotificationLayer: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    zIndex: 360,
    elevation: 360,
  },
  llmCompletionNotificationHost: {
    flex: 1,
  },
  llmCompletionNotificationWidget: {
    position: "absolute",
    alignItems: "flex-end",
  },
  llmCompletionNotificationStack: {
    width: "100%",
    gap: 8,
  },
  llmCompletionNotificationCompact: {
    width: 48,
    height: 48,
    borderRadius: 24,
    borderWidth: theme.borders.thin,
    borderColor: theme.colors.primaryActionOutlineSoft,
    backgroundColor: theme.colors.floatingSurface,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: theme.colors.textPrimary,
    shadowOpacity: 0.18,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 8,
  },
  llmCompletionNotificationCountBadge: {
    position: "absolute",
    top: -3,
    right: -3,
    minWidth: 20,
    height: 20,
    borderRadius: 10,
    paddingHorizontal: 5,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: theme.colors.primaryAction,
    borderWidth: theme.borders.strong,
    borderColor: theme.colors.surface,
  },
  llmCompletionNotificationCountText: {
    color: theme.colors.textOnAccent,
    fontSize: theme.typography.caption.fontSize,
    lineHeight: theme.typography.caption.lineHeight,
    fontWeight: "800",
  },
  llmCompletionNotificationCardMotion: {
    width: "100%",
  },
  llmCompletionNotificationCard: {
    width: "100%",
    minHeight: 58,
    borderRadius: 8,
    borderWidth: theme.borders.thin,
    borderColor: theme.colors.borderTranslucent,
    backgroundColor: theme.colors.floatingSurface,
    paddingLeft: 12,
    paddingRight: 36,
    paddingTop: 10,
    paddingBottom: 10,
    shadowColor: theme.colors.textPrimary,
    shadowOpacity: 0.16,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    overflow: "hidden",
  },
  llmCompletionNotificationClose: {
    position: "absolute",
    top: 7,
    right: 7,
    width: 26,
    height: 26,
    borderRadius: 13,
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  llmCompletionNotificationDirectory: {
    marginBottom: 4,
    color: theme.colors.primaryAction,
    fontSize: theme.typography.caption.fontSize,
    lineHeight: theme.typography.caption.lineHeight,
    fontWeight: "700",
    letterSpacing: 0,
  },
  llmCompletionNotificationPreview: {
    color: theme.colors.textSecondary,
    fontSize: theme.typography.small.fontSize,
    lineHeight: theme.typography.small.lineHeight,
    fontWeight: "500",
    letterSpacing: 0,
  },
  chatScreen: {
    flex: 1,
    minHeight: 0,
    paddingHorizontal: 12,
    paddingTop: 8,
    paddingBottom: 10,
    gap: 8,
    backgroundColor: theme.colors.canvas,
  },
  chatKeyboardAvoiding: {
    flex: 1,
    minHeight: 0,
    overflow: "hidden",
  },
  chatKeyboardAvoidingContent: {
    flex: 1,
    minHeight: 0,
  },
  chatKeyboardAvoidingBody: {
    flex: 1,
    minHeight: 0,
    gap: 8,
  },
  chatHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
    marginBottom: 2,
    zIndex: 10,
    elevation: 10,
    backgroundColor: theme.colors.canvas,
  },
  chatHeaderLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    flex: 1,
    minWidth: 0,
  },
  chatHeaderRight: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    flexShrink: 0,
  },
  chatFindBar: {
    position: "absolute",
    top: 8,
    right: 12,
    zIndex: 20,
    elevation: 20,
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    padding: 4,
    borderWidth: theme.borders.thin,
    borderColor: theme.colors.border,
    borderRadius: 8,
    backgroundColor: theme.colors.surface,
    shadowColor: theme.colors.textPrimary,
    shadowOpacity: 0.12,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
  },
  chatFindInput: {
    width: 200,
    height: 28,
    paddingHorizontal: 7,
    paddingVertical: 3,
    borderWidth: theme.borders.thin,
    borderColor: theme.colors.border,
    borderRadius: 5,
    color: theme.colors.textPrimary,
    backgroundColor: theme.colors.surface,
    fontSize: theme.typography.compact.fontSize,
  },
  chatFindCount: {
    width: 58,
    color: theme.colors.textMuted,
    fontSize: theme.typography.small.fontSize,
    textAlign: "center",
  },
  chatFindButton: {
    width: 28,
    height: 28,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 5,
  },
  chatFindButtonDisabled: {
    opacity: 0.35,
  },
  menuButton: {
    width: 40,
    height: 40,
    borderRadius: 10,
    borderWidth: 0,
    backgroundColor: theme.colors.surface,
    alignItems: "center",
    justifyContent: "center",
  },
  menuButtonText: {
    fontSize: theme.typography.sectionTitle.fontSize,
    fontWeight: "700",
    color: theme.colors.textStrong,
    marginTop: -2,
  },
  gitDiffHeaderButton: {
    minHeight: 34,
    maxWidth: 124,
    paddingHorizontal: 4,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
  },
  gitDiffHeaderBehindText: {
    fontSize: theme.typography.compact.fontSize,
    fontWeight: "700",
    color: theme.colors.accent,
  },
  gitDiffHeaderSummary: {
    maxWidth: 88,
    alignItems: "center",
    gap: 1,
  },
  gitDiffHeaderBranchText: {
    maxWidth: 88,
    fontSize: theme.typography.caption.fontSize,
    fontWeight: "800",
    color: theme.colors.textSecondary,
    lineHeight: theme.typography.micro.lineHeight,
  },
  gitDiffHeaderCountRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  gitDiffHeaderButtonPlusText: {
    fontSize: theme.typography.compact.fontSize,
    fontWeight: "700",
    color: theme.colors.positiveText,
  },
  gitDiffHeaderButtonMinusText: {
    fontSize: theme.typography.compact.fontSize,
    fontWeight: "700",
    color: theme.colors.negativeText,
  },
  pixelRobotWrap: {
    width: 40,
    height: 40,
    alignItems: "center",
    justifyContent: "center",
  },
  pixelRobotImage: {
    width: 36,
    height: 36,
    alignSelf: "center",
    borderRadius: 999,
    overflow: "hidden",
  },
  chatContextRingWrap: {
    width: 36,
    height: 36,
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
  },
  chatContextWrap: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    flexShrink: 0,
  },
  chatDirectoryHeaderButton: {
    minWidth: 0,
    flexGrow: 1,
    flexShrink: 1,
    borderRadius: 10,
    paddingHorizontal: 8,
    paddingVertical: 8,
  },
  chatDirectoryHeaderButtonText: {
    color: theme.colors.textPrimary,
    fontSize: theme.typography.input.fontSize,
    fontWeight: "400",
  },
  chatDirectoryHeaderPrimaryRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  chatDirectoryHeaderMarkerDot: {
    width: 8,
    height: 8,
    borderRadius: 999,
    borderWidth: theme.borders.thin,
    borderColor: theme.colors.borderTranslucent,
  },
  chatDirectoryHeaderSessionTitleText: {
    color: theme.colors.textMuted,
    fontSize: theme.typography.caption.fontSize,
    fontWeight: "800",
    lineHeight: theme.typography.caption.lineHeight,
  },
  chatSelectionRequiredWrap: {
    flex: 1,
    borderWidth: theme.borders.thin,
    borderColor: theme.colors.borderSubtle,
    borderRadius: 12,
    backgroundColor: theme.colors.surfaceRaised,
    paddingHorizontal: 14,
    paddingVertical: 14,
    gap: 10,
  },
  chatSelectionRequiredTitle: {
    fontSize: theme.typography.control.fontSize,
    color: theme.colors.textPrimary,
    fontWeight: "800",
  },
  chatSelectionRequiredHint: {
    fontSize: theme.typography.compact.fontSize,
    lineHeight: theme.typography.body.lineHeight,
    color: theme.colors.textMuted,
  },
  chatSelectionRequiredButton: {
    alignSelf: "flex-start",
    borderWidth: theme.borders.thin,
    borderColor: theme.colors.primaryAction,
    borderRadius: 10,
    backgroundColor: theme.colors.surfaceActionSoft,
    paddingHorizontal: 12,
    paddingVertical: 9,
  },
  chatSelectionRequiredButtonText: {
    fontSize: theme.typography.compact.fontSize,
    fontWeight: "700",
    color: theme.colors.primaryAction,
  },
  chatDirectoryRenameBlock: {
    gap: 10,
  },
  chatDirectoryModalCard: {
    width: "100%",
    maxHeight: "85%",
    overflow: "hidden",
    borderRadius: 22,
    backgroundColor: theme.colors.surfaceGrouped,
  },
  chatDirectoryModalScroll: {
    flexShrink: 1,
  },
  chatDirectoryModalContent: {
    paddingHorizontal: 18,
    paddingTop: 18,
    paddingBottom: 28,
    gap: 22,
  },
  chatDirectoryModalHeader: {
    gap: 4,
  },
  chatDirectoryModalBackButton: {
    alignSelf: "flex-start",
    minHeight: 32,
    justifyContent: "center",
  },
  chatDirectoryModalTitle: {
    fontSize: theme.typography.displayLarge.fontSize,
    lineHeight: theme.typography.displayLarge.lineHeight,
    fontWeight: "800",
    color: theme.colors.groupedTextPrimary,
  },
  chatDirectoryMenuPathText: {
    fontSize: theme.typography.small.fontSize,
    color: theme.colors.groupedTextMuted,
    lineHeight: theme.typography.small.lineHeight,
  },
  chatDirectoryRenameTitle: {
    fontSize: theme.typography.body.fontSize,
    color: theme.colors.groupedTextPrimary,
    fontWeight: "600",
  },
  chatDirectoryEditorGroup: {
    paddingVertical: 14,
  },
  chatDirectoryRenameInput: {
    backgroundColor: theme.colors.surface,
    borderRadius: 10,
    borderWidth: theme.borders.thin,
    borderColor: theme.colors.groupedBorder,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: theme.typography.input.fontSize,
    color: theme.colors.controlTextPrimary,
  },
  chatDirectoryRenameInputRow: {
    position: "relative",
    justifyContent: "center",
  },
  chatDirectoryRenameInputWithClear: {
    paddingRight: 44,
  },
  chatDirectoryRenameInputClearButton: {
    position: "absolute",
    right: 8,
    width: 28,
    height: 28,
    borderRadius: 999,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: theme.colors.surfaceSubtle,
  },
  chatDirectoryRenameActions: {
    flexDirection: "row",
    gap: 8,
  },
  chatDirectoryRenamePrimaryButton: {
    flex: 1,
    minHeight: 44,
    borderRadius: 10,
    backgroundColor: theme.colors.controlAccent,
    alignItems: "center",
    justifyContent: "center",
  },
  chatDirectoryRenamePrimaryButtonText: {
    color: theme.colors.textOnAccent,
    fontSize: theme.typography.input.fontSize,
    fontWeight: "700",
  },
  chatDirectoryRenameSecondaryButton: {
    flex: 1,
    minHeight: 44,
    borderRadius: 10,
    backgroundColor: theme.colors.groupedDivider,
    alignItems: "center",
    justifyContent: "center",
  },
  chatDirectoryRenameSecondaryButtonText: {
    color: theme.colors.groupedTextPrimary,
    fontSize: theme.typography.input.fontSize,
    fontWeight: "700",
  },
  chatDirectoryMenuOption: {
    minHeight: 58,
    paddingVertical: 11,
    justifyContent: "center",
  },
  chatDirectoryMenuOptionText: {
    flex: 1,
    fontSize: theme.typography.input.fontSize,
    color: theme.colors.groupedTextPrimary,
    fontWeight: "600",
  },
  chatDirectorySubagentSection: {
    gap: 22,
  },
  chatDirectorySubagentSectionTitle: {
    paddingHorizontal: 10,
    fontSize: theme.typography.subtitle.fontSize,
    lineHeight: theme.typography.subtitleDense.lineHeight,
    color: theme.colors.groupedTextMuted,
    fontWeight: "700",
  },
  chatDirectorySubagentOption: {
    minHeight: 58,
    paddingVertical: 11,
    justifyContent: "center",
  },
  chatDirectorySubagentOptionText: {
    fontSize: theme.typography.input.fontSize,
    lineHeight: theme.typography.body.lineHeight,
    color: theme.colors.groupedTextPrimary,
    fontWeight: "600",
  },
  chatDirectorySubagentStatusRow: {
    minHeight: 58,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  chatDirectorySubagentMetaText: {
    marginTop: 2,
    fontSize: theme.typography.caption.fontSize,
    color: theme.colors.groupedTextMuted,
    lineHeight: theme.typography.captionDense.lineHeight,
  },
  chatDirectorySubagentErrorText: {
    fontSize: theme.typography.small.fontSize,
    color: theme.tones.danger.foreground,
    lineHeight: theme.typography.small.lineHeight,
  },
  chatDirectoryMarkerOptionRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  chatDirectoryMarkerOptionDot: {
    width: 12,
    height: 12,
    borderRadius: 999,
    borderWidth: theme.borders.thin,
    borderColor: theme.colors.borderTranslucent,
  },
  chatDirectoryMarkerOptionDotNone: {
    backgroundColor: theme.colors.surface,
  },
  chatContextPctText: {
    fontSize: theme.typography.caption.fontSize,
    color: theme.colors.textPrimary,
    fontWeight: "700",
    textAlign: "center",
  },
  chatContextResetButton: {
    position: "absolute",
    left: 0,
    top: 0,
    width: 36,
    height: 36,
    borderRadius: 999,
    backgroundColor: "transparent",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 3,
  },
  gitDiffPanelOverlayWrap: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    zIndex: 90,
  },
  gitDiffPanelBackdrop: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    backgroundColor: theme.colors.panelBackdrop,
  },
  gitDiffPanelBackdropTouch: {
    flex: 1,
  },
  gitDiffPanel: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    borderLeftWidth: theme.borders.thin,
    borderLeftColor: theme.colors.border,
    backgroundColor: theme.colors.surface,
    shadowColor: theme.colors.textPrimary,
    shadowOpacity: 0.22,
    shadowRadius: 16,
    shadowOffset: { width: -4, height: 0 },
    elevation: 18,
  },
  gitDiffPanelHeader: {
    minHeight: 56,
    borderBottomWidth: theme.borders.thin,
    borderBottomColor: theme.colors.borderSubtle,
    paddingHorizontal: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  gitDiffPanelTitle: {
    fontSize: theme.typography.control.fontSize,
    fontWeight: "700",
    color: theme.colors.textPrimary,
  },
  gitDiffPanelHeaderActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  gitDiffPanelHeaderButton: {
    width: 32,
    height: 32,
    borderRadius: 999,
    borderWidth: theme.borders.thin,
    borderColor: theme.colors.border,
    backgroundColor: theme.colors.surfaceRaised,
    alignItems: "center",
    justifyContent: "center",
  },
  gitDiffPanelTabRow: {
    flexDirection: "row",
    gap: 8,
    paddingHorizontal: 10,
    paddingTop: 8,
    paddingBottom: 4,
    borderBottomWidth: theme.borders.thin,
    borderBottomColor: theme.colors.borderSubtle,
  },
  gitDiffPanelTabButton: {
    flex: 1,
    minHeight: 32,
    borderWidth: theme.borders.thin,
    borderColor: theme.colors.border,
    borderRadius: 8,
    backgroundColor: theme.colors.surfaceRaised,
    alignItems: "center",
    justifyContent: "center",
  },
  gitDiffPanelTabButtonActive: {
    borderColor: theme.colors.primaryAction,
    backgroundColor: theme.colors.surfaceActionSelected,
  },
  gitDiffPanelTabButtonText: {
    fontSize: theme.typography.small.fontSize,
    fontWeight: "600",
    color: theme.colors.textSecondary,
  },
  gitDiffPanelTabButtonTextActive: {
    color: theme.colors.primaryAction,
    fontWeight: "700",
  },
  gitDiffPanelScroll: {
    flex: 1,
  },
  gitDiffPanelScrollContent: {
    paddingHorizontal: 10,
    paddingVertical: 10,
    gap: 10,
  },
  gitDiffPanelStatusRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 2,
  },
  gitDiffPanelStatusText: {
    fontSize: theme.typography.small.fontSize,
    color: theme.colors.textSecondary,
    fontWeight: "600",
  },
  gitDiffPanelErrorText: {
    fontSize: theme.typography.small.fontSize,
    color: theme.tones.danger.foreground,
    lineHeight: theme.typography.compact.lineHeight,
  },
  gitDiffSectionCard: {
    borderWidth: theme.borders.thin,
    borderColor: theme.colors.borderSubtle,
    borderRadius: 10,
    backgroundColor: theme.colors.surface,
    paddingHorizontal: 8,
    paddingVertical: 8,
    gap: 6,
  },
  gitDiffSectionTitle: {
    fontSize: theme.typography.compact.fontSize,
    fontWeight: "700",
    color: theme.colors.textPrimary,
  },
  gitDiffSectionHint: {
    marginTop: -2,
    fontSize: theme.typography.caption.fontSize,
    color: theme.colors.textMuted,
  },
  gitDiffEmptyText: {
    fontSize: theme.typography.small.fontSize,
    color: theme.colors.textMuted,
    lineHeight: theme.typography.compact.lineHeight,
  },
  gitDiffTreeWrap: {
    gap: 0,
  },
  gitDiffTreeNodeWrap: {
    gap: 0,
  },
  gitDiffTreeNodeRow: {
    minHeight: 22,
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  gitDiffTreeNodeIcon: {
    width: 12,
    fontSize: theme.typography.caption.fontSize,
    color: theme.colors.textMuted,
  },
  gitDiffTreeNodeDirText: {
    fontSize: theme.typography.small.fontSize,
    fontWeight: "700",
    color: theme.colors.textStrong,
  },
  gitDiffTreeNodeSpinner: {
    marginLeft: 6,
  },
  gitDiffTreeNodeErrorText: {
    marginLeft: 22,
  },
  gitDiffTreeNodeEmptyText: {
    marginLeft: 22,
  },
  gitDiffTreeNodeFileText: {
    fontSize: theme.typography.small.fontSize,
    color: theme.colors.textSecondary,
  },
  gitDiffRunningJobList: {
    gap: 8,
  },
  gitDiffRunningJobRow: {
    borderWidth: theme.borders.thin,
    borderColor: theme.colors.borderMuted,
    borderRadius: 8,
    backgroundColor: theme.colors.surfaceRaised,
    paddingHorizontal: 8,
    paddingVertical: 7,
    gap: 3,
  },
  gitDiffRunningJobRowHead: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  gitDiffRunningJobPath: {
    flex: 1,
    fontSize: theme.typography.small.fontSize,
    fontWeight: "700",
    color: theme.colors.textStrong,
  },
  gitDiffRunningJobStatus: {
    fontSize: theme.typography.caption.fontSize,
    fontWeight: "700",
  },
  gitDiffRunningJobStatusRunning: {
    color: theme.colors.primaryAction,
  },
  gitDiffRunningJobStatusStopping: {
    color: theme.colors.warningText,
  },
  gitDiffRunningJobStatusCompleted: {
    color: theme.tones.success.foreground,
  },
  gitDiffRunningJobStatusFailed: {
    color: theme.tones.danger.foreground,
  },
  gitDiffRunningJobMeta: {
    fontSize: theme.typography.caption.fontSize,
    color: theme.colors.textMuted,
  },
  gitDiffRunningJobHint: {
    fontSize: theme.typography.micro.fontSize,
    color: theme.colors.textMuted,
    fontWeight: "600",
  },
  chatScroll: {
    flex: 1,
    minHeight: 0,
    backgroundColor: theme.colors.canvas,
  },
  chatScrollEndSentinel: {
    width: 1,
    height: 32,
    opacity: 0,
  },
  chatScrollContent: {
    flexGrow: 1,
    paddingBottom: 12,
    gap: 0,
  },
  popupMessagesSkeleton: {
    flex: 1,
    paddingHorizontal: 4,
    paddingTop: 8,
    gap: 10,
    backgroundColor: theme.colors.canvas,
  },
  popupMessagesSkeletonBubbleWide: {
    alignSelf: "flex-start",
    width: "78%",
    height: 54,
    borderRadius: 14,
    backgroundColor: theme.colors.skeleton,
  },
  popupMessagesSkeletonBubble: {
    alignSelf: "flex-end",
    width: "64%",
    height: 46,
    borderRadius: 14,
    backgroundColor: theme.colors.surfaceSubtle,
  },
  popupMessagesSkeletonBubbleShort: {
    alignSelf: "flex-start",
    width: "48%",
    height: 38,
    borderRadius: 14,
    backgroundColor: theme.colors.skeleton,
  },
  chatSessionRestoreOverlay: {
    position: "absolute",
    left: 0,
    right: 0,
    top: 62,
    bottom: 94,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: theme.colors.restoreOverlay,
    zIndex: 6,
  },
  chatSessionRestoreCard: {
    minWidth: 180,
    borderRadius: 12,
    borderWidth: theme.borders.thin,
    borderColor: theme.colors.border,
    backgroundColor: theme.colors.surface,
    paddingHorizontal: 18,
    paddingVertical: 14,
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
  },
  chatSessionRestoreText: {
    fontSize: theme.typography.compact.fontSize,
    color: theme.colors.textPrimary,
    fontWeight: "600",
  },
  chatSessionRestoreReloadButton: {
    marginTop: 2,
    borderWidth: theme.borders.thin,
    borderColor: theme.colors.border,
    borderRadius: 8,
    backgroundColor: theme.colors.surface,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  chatSessionRestoreReloadButtonText: {
    fontSize: theme.typography.small.fontSize,
    color: theme.colors.textSecondary,
    fontWeight: "700",
  },
  chatEmpty: {
    fontSize: theme.typography.compact.fontSize,
    color: theme.colors.textMuted,
    paddingVertical: 8,
  },
  chatYouTubeQueueHint: {
    marginTop: -2,
    marginBottom: 2,
    fontSize: theme.typography.caption.fontSize,
    color: theme.colors.accentStrong,
    fontWeight: "700",
  },
  chatContextUsageHint: {
    marginTop: -2,
    marginBottom: 2,
    fontSize: theme.typography.caption.fontSize,
    color: theme.colors.primaryAction,
    fontWeight: "700",
  },
  ...chatMessageStylesByTheme[theme.id],
  ...chatComposerStylesByTheme[theme.id],
  } as const;
}

export const appLayoutStylesByTheme: Record<VisualThemeId, ReturnType<typeof createAppLayoutStyles>> = {
  standard: createAppLayoutStyles(VISUAL_THEMES.standard),
  highLegibility: createAppLayoutStyles(VISUAL_THEMES.highLegibility),
};
