import { appCommonStyles } from "./appCommonStyles";
import { chatComposerStyles } from "./chatComposerStyles";
import { chatMessageStyles } from "./chatMessageStyles";

const MINI_BOARD_PAPER = "#fbfaf7";
const MINI_BOARD_INK = "#151515";
const MINI_BOARD_SUB = "#575650";
const MINI_BOARD_MUTED = "#8d8b83";

export const appLayoutStyles = {
  ...appCommonStyles,
  drawerPopupOverlayHost: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    zIndex: 300,
    elevation: 300,
  },
  drawerPopupSafeArea: {
    flex: 1,
    backgroundColor: "transparent",
  },
  llmCompletionNotificationLayer: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    zIndex: 360,
    elevation: 360,
  },
  llmCompletionNotificationHost: {
    flex: 1,
  },
  llmCompletionNotificationWidget: {
    position: "absolute",
    alignItems: "flex-end",
  },
  llmCompletionNotificationStack: {
    width: "100%",
    gap: 8,
  },
  llmCompletionNotificationCompact: {
    width: 48,
    height: 48,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: "rgba(15, 118, 110, 0.22)",
    backgroundColor: "rgba(255, 255, 255, 0.97)",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#0f172a",
    shadowOpacity: 0.18,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 8,
  },
  llmCompletionNotificationCountBadge: {
    position: "absolute",
    top: -3,
    right: -3,
    minWidth: 20,
    height: 20,
    borderRadius: 10,
    paddingHorizontal: 5,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#0f766e",
    borderWidth: 2,
    borderColor: "#ffffff",
  },
  llmCompletionNotificationCountText: {
    color: "#ffffff",
    fontSize: 11,
    lineHeight: 14,
    fontWeight: "800",
  },
  llmCompletionNotificationCardMotion: {
    width: "100%",
  },
  llmCompletionNotificationCard: {
    width: "100%",
    minHeight: 58,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "rgba(15, 23, 42, 0.12)",
    backgroundColor: "rgba(255, 255, 255, 0.97)",
    paddingLeft: 12,
    paddingRight: 36,
    paddingTop: 10,
    paddingBottom: 10,
    shadowColor: "#0f172a",
    shadowOpacity: 0.16,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    overflow: "hidden",
  },
  llmCompletionNotificationClose: {
    position: "absolute",
    top: 7,
    right: 7,
    width: 26,
    height: 26,
    borderRadius: 13,
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  llmCompletionNotificationDirectory: {
    marginBottom: 4,
    color: "#0f766e",
    fontSize: 11,
    lineHeight: 14,
    fontWeight: "700",
    letterSpacing: 0,
  },
  llmCompletionNotificationPreview: {
    color: "#334155",
    fontSize: 12,
    lineHeight: 17,
    fontWeight: "500",
    letterSpacing: 0,
  },
  chatScreen: {
    flex: 1,
    minHeight: 0,
    paddingHorizontal: 12,
    paddingTop: 8,
    paddingBottom: 10,
    gap: 8,
    backgroundColor: "#ffffff",
  },
  miniBoardPreviewChatScreen: {
    position: "relative",
    paddingHorizontal: 0,
    paddingTop: 0,
    paddingBottom: 0,
    gap: 0,
    backgroundColor: MINI_BOARD_PAPER,
  },
  miniBoardPreviewChatHeader: {
    position: "relative",
    alignItems: "flex-start",
    marginBottom: 0,
    minHeight: 32,
    backgroundColor: MINI_BOARD_PAPER,
  },
  miniBoardPreviewChatHeaderLeft: {
    paddingRight: 44,
  },
  miniBoardPreviewChatHeaderRight: {
    position: "absolute",
    top: 0,
    right: 0,
  },
  miniBoardPreviewChatDirectoryButton: {
    paddingHorizontal: 0,
    paddingVertical: 0,
    borderRadius: 0,
  },
  miniBoardPreviewChatDirectoryPrimaryRow: {
    alignItems: "baseline",
    gap: 7,
  },
  miniBoardPreviewChatMarkerDot: {
    width: 8,
    height: 8,
    borderColor: "rgba(21, 21, 17, 0.14)",
  },
  miniBoardPreviewChatTitle: {
    color: MINI_BOARD_INK,
    fontSize: 15,
    lineHeight: 17,
    fontWeight: "700",
    letterSpacing: 0,
  },
  miniBoardPreviewChatSubtitle: {
    marginTop: 6,
    paddingLeft: 15,
    color: MINI_BOARD_MUTED,
    fontSize: 11,
    lineHeight: 14,
    fontWeight: "500",
    letterSpacing: 0,
  },
  miniBoardPreviewChatContextWrap: {
    gap: 0,
  },
  miniBoardPreviewChatContextRingWrap: {
    width: 40,
    height: 18,
    overflow: "hidden",
  },
  miniBoardPreviewChatContextPctButton: {
    left: -2,
    top: -2,
    width: 44,
    height: 22,
    borderRadius: 0,
    backgroundColor: MINI_BOARD_PAPER,
  },
  miniBoardPreviewChatContextPctText: {
    minWidth: 34,
    color: MINI_BOARD_SUB,
    fontSize: 11,
    lineHeight: 13,
    fontWeight: "600",
    textAlign: "right",
    letterSpacing: 0,
  },
  miniBoardPreviewChatScroll: {
    marginTop: 15,
    backgroundColor: MINI_BOARD_PAPER,
  },
  miniBoardPreviewChatMessageGroup: {
    marginBottom: 8,
    gap: 0,
  },
  miniBoardPreviewChatBubble: {
    maxWidth: "100%",
    width: "100%",
    paddingHorizontal: 0,
    paddingVertical: 0,
    borderRadius: 0,
    backgroundColor: "transparent",
  },
  miniBoardPreviewChatBubbleText: {
    color: MINI_BOARD_SUB,
    fontSize: 12,
    lineHeight: 18,
    fontWeight: "500",
    letterSpacing: 0,
  },
  miniBoardPreviewChatEmpty: {
    color: MINI_BOARD_MUTED,
    fontSize: 12,
    lineHeight: 18,
    paddingVertical: 0,
  },
  miniChatRespondingBadge: {
    position: "absolute",
    left: 4,
    bottom: 4,
    zIndex: 30,
    elevation: 30,
    width: 34,
    height: 34,
    alignItems: "center",
    justifyContent: "center",
  },
  miniBoardPreviewUpdatedAtBadge: {
    position: "absolute",
    right: -5,
    bottom: -8,
    zIndex: 32,
    elevation: 32,
    borderRadius: 999,
    backgroundColor: "rgba(251, 250, 247, 0.92)",
    paddingLeft: 3,
    paddingTop: 3,
  },
  miniBoardPreviewUpdatedAtText: {
    color: MINI_BOARD_MUTED,
    fontSize: 10,
    lineHeight: 12,
    fontWeight: "700",
    letterSpacing: 0,
  },
  chatKeyboardAvoiding: {
    flex: 1,
    minHeight: 0,
    overflow: "hidden",
  },
  chatKeyboardAvoidingContent: {
    flex: 1,
    minHeight: 0,
  },
  chatKeyboardAvoidingBody: {
    flex: 1,
    minHeight: 0,
    gap: 8,
  },
  chatHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
    marginBottom: 2,
    zIndex: 10,
    elevation: 10,
    backgroundColor: "#ffffff",
  },
  chatHeaderLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    flex: 1,
    minWidth: 0,
  },
  chatHeaderRight: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    flexShrink: 0,
  },
  menuButton: {
    width: 40,
    height: 40,
    borderRadius: 10,
    borderWidth: 0,
    backgroundColor: "#ffffff",
    alignItems: "center",
    justifyContent: "center",
  },
  menuButtonText: {
    fontSize: 20,
    fontWeight: "700",
    color: "#1e293b",
    marginTop: -2,
  },
  gitDiffHeaderButton: {
    minHeight: 34,
    maxWidth: 124,
    paddingHorizontal: 4,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
  },
  gitDiffHeaderBehindText: {
    fontSize: 13,
    fontWeight: "700",
    color: "#2563eb",
  },
  gitDiffHeaderSummary: {
    maxWidth: 88,
    alignItems: "center",
    gap: 1,
  },
  gitDiffHeaderBranchText: {
    maxWidth: 88,
    fontSize: 11,
    fontWeight: "800",
    color: "#334155",
    lineHeight: 13,
  },
  gitDiffHeaderCountRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  gitDiffHeaderButtonPlusText: {
    fontSize: 13,
    fontWeight: "700",
    color: "#16a34a",
  },
  gitDiffHeaderButtonMinusText: {
    fontSize: 13,
    fontWeight: "700",
    color: "#dc2626",
  },
  pixelRobotWrap: {
    width: 40,
    height: 40,
    alignItems: "center",
    justifyContent: "center",
  },
  pixelRobotImage: {
    width: 36,
    height: 36,
    alignSelf: "center",
    borderRadius: 999,
    overflow: "hidden",
  },
  chatContextRingWrap: {
    width: 36,
    height: 36,
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
  },
  chatContextWrap: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    flexShrink: 0,
  },
  chatDirectoryHeaderButton: {
    minWidth: 0,
    flexGrow: 1,
    flexShrink: 1,
    borderRadius: 10,
    paddingHorizontal: 8,
    paddingVertical: 8,
  },
  chatDirectoryHeaderButtonText: {
    color: "#0f172a",
    fontSize: 15,
    fontWeight: "400",
  },
  chatDirectoryHeaderPrimaryRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  chatDirectoryHeaderMarkerDot: {
    width: 8,
    height: 8,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "rgba(15, 23, 42, 0.12)",
  },
  chatDirectoryHeaderSessionTitleText: {
    color: "#64748b",
    fontSize: 11,
    fontWeight: "800",
    lineHeight: 14,
  },
  chatSelectionRequiredWrap: {
    flex: 1,
    borderWidth: 1,
    borderColor: "#e2e8f0",
    borderRadius: 12,
    backgroundColor: "#f8fafc",
    paddingHorizontal: 14,
    paddingVertical: 14,
    gap: 10,
  },
  chatSelectionRequiredTitle: {
    fontSize: 16,
    color: "#0f172a",
    fontWeight: "800",
  },
  chatSelectionRequiredHint: {
    fontSize: 13,
    lineHeight: 20,
    color: "#475569",
  },
  chatSelectionRequiredButton: {
    alignSelf: "flex-start",
    borderWidth: 1,
    borderColor: "#0f766e",
    borderRadius: 10,
    backgroundColor: "#f0fdfa",
    paddingHorizontal: 12,
    paddingVertical: 9,
  },
  chatSelectionRequiredButtonText: {
    fontSize: 13,
    fontWeight: "700",
    color: "#0f766e",
  },
  chatDirectoryRenameBlock: {
    gap: 10,
  },
  chatDirectoryModalCard: {
    borderRadius: 14,
    backgroundColor: "#ffffff",
    borderWidth: 1,
    borderColor: "#e5e7eb",
    paddingHorizontal: 14,
    paddingVertical: 14,
    gap: 12,
  },
  chatDirectoryModalTitle: {
    fontSize: 17,
    fontWeight: "700",
    color: "#0f172a",
  },
  chatDirectoryMenuPathText: {
    marginTop: -4,
    fontSize: 13,
    color: "#64748b",
    lineHeight: 19,
  },
  chatDirectoryRenameTitle: {
    fontSize: 14,
    color: "#1e293b",
    fontWeight: "600",
  },
  chatDirectoryRenameInput: {
    backgroundColor: "#ffffff",
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#d1d5db",
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 15,
    color: "#111827",
  },
  chatDirectoryRenameInputRow: {
    position: "relative",
    justifyContent: "center",
  },
  chatDirectoryRenameInputWithClear: {
    paddingRight: 44,
  },
  chatDirectoryRenameInputClearButton: {
    position: "absolute",
    right: 8,
    width: 28,
    height: 28,
    borderRadius: 999,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#e2e8f0",
  },
  chatDirectoryRenameActions: {
    flexDirection: "row",
    gap: 8,
  },
  chatDirectoryRenamePrimaryButton: {
    flex: 1,
    minHeight: 44,
    borderRadius: 10,
    backgroundColor: "#0f766e",
    alignItems: "center",
    justifyContent: "center",
  },
  chatDirectoryRenamePrimaryButtonText: {
    color: "#ffffff",
    fontSize: 15,
    fontWeight: "700",
  },
  chatDirectoryRenameSecondaryButton: {
    flex: 1,
    minHeight: 44,
    borderRadius: 10,
    backgroundColor: "#e2e8f0",
    alignItems: "center",
    justifyContent: "center",
  },
  chatDirectoryRenameSecondaryButtonText: {
    color: "#1e293b",
    fontSize: 15,
    fontWeight: "700",
  },
  chatDirectoryMenuOption: {
    minHeight: 46,
    borderRadius: 10,
    backgroundColor: "#f8fafc",
    paddingHorizontal: 12,
    paddingVertical: 10,
    justifyContent: "center",
  },
  chatDirectoryMenuOptionText: {
    fontSize: 15,
    color: "#0f172a",
    fontWeight: "600",
  },
  chatDirectorySubagentSection: {
    gap: 8,
    paddingTop: 2,
  },
  chatDirectorySubagentSectionTitle: {
    fontSize: 12,
    color: "#64748b",
    fontWeight: "700",
    textTransform: "uppercase",
  },
  chatDirectorySubagentOption: {
    minHeight: 48,
    borderRadius: 10,
    backgroundColor: "#f8fafc",
    paddingHorizontal: 12,
    paddingVertical: 8,
    justifyContent: "center",
  },
  chatDirectorySubagentOptionText: {
    fontSize: 14,
    color: "#0f172a",
    fontWeight: "700",
  },
  chatDirectorySubagentStatusRow: {
    minHeight: 32,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  chatDirectorySubagentMetaText: {
    fontSize: 12,
    color: "#64748b",
    lineHeight: 17,
  },
  chatDirectorySubagentErrorText: {
    fontSize: 12,
    color: "#b91c1c",
    lineHeight: 17,
  },
  chatDirectoryMarkerOptionRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  chatDirectoryMarkerOptionDot: {
    width: 12,
    height: 12,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "rgba(15, 23, 42, 0.16)",
  },
  chatDirectoryMarkerOptionDotNone: {
    backgroundColor: "#ffffff",
  },
  chatDirectoryMenuDangerText: {
    fontSize: 15,
    color: "#b91c1c",
    fontWeight: "600",
  },
  chatContextPctText: {
    fontSize: 11,
    color: "#0f172a",
    fontWeight: "700",
    textAlign: "center",
  },
  chatContextResetButton: {
    position: "absolute",
    left: 0,
    top: 0,
    width: 36,
    height: 36,
    borderRadius: 999,
    backgroundColor: "transparent",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 3,
  },
  gitDiffPanelOverlayWrap: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    zIndex: 90,
  },
  gitDiffPanelBackdrop: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    backgroundColor: "rgba(2, 6, 23, 0.28)",
  },
  gitDiffPanelBackdropTouch: {
    flex: 1,
  },
  gitDiffPanel: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    borderLeftWidth: 1,
    borderLeftColor: "#cbd5e1",
    backgroundColor: "#ffffff",
    shadowColor: "#0f172a",
    shadowOpacity: 0.22,
    shadowRadius: 16,
    shadowOffset: { width: -4, height: 0 },
    elevation: 18,
  },
  gitDiffPanelHeader: {
    minHeight: 56,
    borderBottomWidth: 1,
    borderBottomColor: "#e2e8f0",
    paddingHorizontal: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  gitDiffPanelTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: "#0f172a",
  },
  gitDiffPanelHeaderActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  gitDiffPanelHeaderButton: {
    width: 32,
    height: 32,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "#cbd5e1",
    backgroundColor: "#f8fafc",
    alignItems: "center",
    justifyContent: "center",
  },
  gitDiffPanelTabRow: {
    flexDirection: "row",
    gap: 8,
    paddingHorizontal: 10,
    paddingTop: 8,
    paddingBottom: 4,
    borderBottomWidth: 1,
    borderBottomColor: "#e2e8f0",
  },
  gitDiffPanelTabButton: {
    flex: 1,
    minHeight: 32,
    borderWidth: 1,
    borderColor: "#cbd5e1",
    borderRadius: 8,
    backgroundColor: "#f8fafc",
    alignItems: "center",
    justifyContent: "center",
  },
  gitDiffPanelTabButtonActive: {
    borderColor: "#0f766e",
    backgroundColor: "#ecfeff",
  },
  gitDiffPanelTabButtonText: {
    fontSize: 12,
    fontWeight: "600",
    color: "#334155",
  },
  gitDiffPanelTabButtonTextActive: {
    color: "#0f766e",
    fontWeight: "700",
  },
  gitDiffPanelScroll: {
    flex: 1,
  },
  gitDiffPanelScrollContent: {
    paddingHorizontal: 10,
    paddingVertical: 10,
    gap: 10,
  },
  gitDiffPanelStatusRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 2,
  },
  gitDiffPanelStatusText: {
    fontSize: 12,
    color: "#334155",
    fontWeight: "600",
  },
  gitDiffPanelErrorText: {
    fontSize: 12,
    color: "#b91c1c",
    lineHeight: 18,
  },
  gitDiffSectionCard: {
    borderWidth: 1,
    borderColor: "#e2e8f0",
    borderRadius: 10,
    backgroundColor: "#ffffff",
    paddingHorizontal: 8,
    paddingVertical: 8,
    gap: 6,
  },
  gitDiffSectionTitle: {
    fontSize: 13,
    fontWeight: "700",
    color: "#0f172a",
  },
  gitDiffSectionHint: {
    marginTop: -2,
    fontSize: 11,
    color: "#64748b",
  },
  gitDiffEmptyText: {
    fontSize: 12,
    color: "#64748b",
    lineHeight: 18,
  },
  gitDiffTreeWrap: {
    gap: 0,
  },
  gitDiffTreeNodeWrap: {
    gap: 0,
  },
  gitDiffTreeNodeRow: {
    minHeight: 22,
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  gitDiffTreeNodeIcon: {
    width: 12,
    fontSize: 11,
    color: "#475569",
  },
  gitDiffTreeNodeDirText: {
    fontSize: 12,
    fontWeight: "700",
    color: "#1e293b",
  },
  gitDiffTreeNodeSpinner: {
    marginLeft: 6,
  },
  gitDiffTreeNodeErrorText: {
    marginLeft: 22,
  },
  gitDiffTreeNodeEmptyText: {
    marginLeft: 22,
  },
  gitDiffTreeNodeFileText: {
    fontSize: 12,
    color: "#334155",
  },
  gitDiffRunningJobList: {
    gap: 8,
  },
  gitDiffRunningJobRow: {
    borderWidth: 1,
    borderColor: "#dbe3ee",
    borderRadius: 8,
    backgroundColor: "#f8fafc",
    paddingHorizontal: 8,
    paddingVertical: 7,
    gap: 3,
  },
  gitDiffRunningJobRowHead: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  gitDiffRunningJobPath: {
    flex: 1,
    fontSize: 12,
    fontWeight: "700",
    color: "#1e293b",
  },
  gitDiffRunningJobStatus: {
    fontSize: 11,
    fontWeight: "700",
  },
  gitDiffRunningJobStatusRunning: {
    color: "#0f766e",
  },
  gitDiffRunningJobStatusStopping: {
    color: "#b45309",
  },
  gitDiffRunningJobStatusCompleted: {
    color: "#166534",
  },
  gitDiffRunningJobStatusFailed: {
    color: "#b91c1c",
  },
  gitDiffRunningJobMeta: {
    fontSize: 11,
    color: "#475569",
  },
  gitDiffRunningJobHint: {
    fontSize: 10,
    color: "#64748b",
    fontWeight: "600",
  },
  chatScroll: {
    flex: 1,
    minHeight: 0,
    backgroundColor: "#ffffff",
  },
  chatScrollEndSentinel: {
    width: 1,
    height: 32,
    opacity: 0,
  },
  chatScrollContent: {
    flexGrow: 1,
    paddingBottom: 12,
    gap: 0,
  },
  popupMessagesSkeleton: {
    flex: 1,
    paddingHorizontal: 4,
    paddingTop: 8,
    gap: 10,
    backgroundColor: "#ffffff",
  },
  popupMessagesSkeletonBubbleWide: {
    alignSelf: "flex-start",
    width: "78%",
    height: 54,
    borderRadius: 14,
    backgroundColor: "#e5e7eb",
  },
  popupMessagesSkeletonBubble: {
    alignSelf: "flex-end",
    width: "64%",
    height: 46,
    borderRadius: 14,
    backgroundColor: "#e2e8f0",
  },
  popupMessagesSkeletonBubbleShort: {
    alignSelf: "flex-start",
    width: "48%",
    height: 38,
    borderRadius: 14,
    backgroundColor: "#e5e7eb",
  },
  miniBoardPreviewChatScrollContent: {
    paddingBottom: 0,
  },
  chatSessionRestoreOverlay: {
    position: "absolute",
    left: 0,
    right: 0,
    top: 62,
    bottom: 94,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(248, 250, 252, 0.56)",
    zIndex: 6,
  },
  chatSessionRestoreCard: {
    minWidth: 180,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#cbd5e1",
    backgroundColor: "#ffffff",
    paddingHorizontal: 18,
    paddingVertical: 14,
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
  },
  chatSessionRestoreText: {
    fontSize: 13,
    color: "#0f172a",
    fontWeight: "600",
  },
  chatSessionRestoreReloadButton: {
    marginTop: 2,
    borderWidth: 1,
    borderColor: "#cbd5e1",
    borderRadius: 8,
    backgroundColor: "#ffffff",
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  chatSessionRestoreReloadButtonText: {
    fontSize: 12,
    color: "#334155",
    fontWeight: "700",
  },
  chatEmpty: {
    fontSize: 13,
    color: "#64748b",
    paddingVertical: 8,
  },
  chatYouTubeQueueHint: {
    marginTop: -2,
    marginBottom: 2,
    fontSize: 11,
    color: "#1d4ed8",
    fontWeight: "700",
  },
  chatContextUsageHint: {
    marginTop: -2,
    marginBottom: 2,
    fontSize: 11,
    color: "#0f766e",
    fontWeight: "700",
  },
  ...chatMessageStyles,
  ...chatComposerStyles,
} as const;
