export const chatComposerStyles = {
  chatComposer: {
    position: "relative",
    gap: 8,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: "#e2e8f0",
  },
  connectionStatusArea: {
    position: "absolute",
    right: 0,
    top: -36,
    zIndex: 20,
    elevation: 20,
    alignItems: "flex-end",
  },
  chatInputWrapper: {
    flexDirection: "row",
    alignItems: "flex-end",
    gap: 8,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#cbd5e1",
    backgroundColor: "#ffffff",
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  chatInput: {
    minHeight: 44,
    maxHeight: 160,
    borderRadius: 0,
    borderWidth: 0,
    borderColor: "transparent",
    backgroundColor: "transparent",
    color: "#111827",
    fontSize: 15,
    paddingHorizontal: 0,
    paddingVertical: 0,
  },
  chatComposerInput: {
    flex: 1,
  },
  chatComposerInputArea: {
    flex: 1,
    minWidth: 0,
    position: "relative",
  },
  chatComposerInputWithExpandButton: {
    paddingRight: 34,
  },
  chatComposerExpandButton: {
    position: "absolute",
    right: 0,
    top: 0,
    width: 28,
    height: 28,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#cbd5e1",
    backgroundColor: "#ffffff",
    alignItems: "center",
    justifyContent: "center",
  },
  chatWaveformBox: {
    flex: 1,
    marginTop: 0,
    marginBottom: 0,
    height: 54,
    paddingHorizontal: 0,
    paddingVertical: 0,
    borderWidth: 0,
  },
  chatDirectSttBox: {
    flex: 1,
    minHeight: 54,
    maxHeight: 108,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#e2e8f0",
    backgroundColor: "#f8fafc",
    paddingHorizontal: 10,
    paddingVertical: 6,
    gap: 4,
    justifyContent: "center",
  },
  chatDirectSttLabel: {
    fontSize: 10,
    fontWeight: "700",
    color: "#64748b",
    textTransform: "uppercase",
    letterSpacing: 0.3,
  },
  chatDirectSttText: {
    fontSize: 14,
    lineHeight: 20,
    color: "#0f172a",
  },
  chatComposerIconRow: {
    flexDirection: "row",
    gap: 8,
    justifyContent: "flex-end",
    alignSelf: "flex-end",
  },
  chatAbButton: {
    minWidth: 56,
    height: 42,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#cbd5e1",
    backgroundColor: "#ffffff",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 8,
  },
  chatAbButtonActive: {
    borderColor: "#b91c1c",
    backgroundColor: "#fee2e2",
  },
  chatAbButtonText: {
    color: "#334155",
    fontSize: 12,
    fontWeight: "800",
    letterSpacing: 0.2,
  },
  chatAbButtonTextActive: {
    color: "#991b1b",
  },
  chatIconButton: {
    width: 42,
    height: 42,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
  },
  chatRecordIconButton: {
    backgroundColor: "#334155",
    borderColor: "#334155",
  },
  chatFaceTrackIconButton: {
    backgroundColor: "#f1f5f9",
    borderColor: "#cbd5e1",
  },
  chatFaceTrackIconButtonEnabled: {
    backgroundColor: "#dcfce7",
    borderColor: "#16a34a",
  },
  chatFaceTrackIconButtonBlocked: {
    backgroundColor: "#ffedd5",
    borderColor: "#ea580c",
  },
  chatFaceTrackIconButtonIdle: {
    backgroundColor: "#f8fafc",
    borderColor: "#94a3b8",
  },
  chatSlashIconButton: {
    backgroundColor: "#ffffff",
    borderColor: "#cbd5e1",
  },
  chatSlashIconText: {
    color: "#334155",
    fontSize: 18,
    fontWeight: "800",
    marginTop: -1,
  },
  chatActionRow: {
    flexDirection: "row",
    gap: 8,
  },
  chatPrimaryButton: {
    flex: 1,
    borderRadius: 10,
    backgroundColor: "#0f766e",
    paddingVertical: 11,
    alignItems: "center",
  },
  chatSecondaryButton: {
    flex: 1,
    borderRadius: 10,
    backgroundColor: "#334155",
    paddingVertical: 11,
    alignItems: "center",
  },
  chatButtonText: {
    color: "#ffffff",
    fontSize: 14,
    fontWeight: "700",
  },
  chatHint: {
    color: "#64748b",
    fontSize: 12,
  },
  chatFooterSettingsRow: {
    marginTop: 2,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 2,
    position: "relative",
  },
  chatFooterSettingsInline: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
    gap: 8,
  },
  chatFooterSettingsText: {
    fontSize: 12,
    color: "#475569",
    textDecorationLine: "underline",
  },
  chatThreadStatusCenter: {
    position: "absolute",
    left: 84,
    right: 84,
    alignItems: "center",
  },
  chatThreadStatusText: {
    color: "#64748b",
    fontSize: 11,
  },
  chatStatusSummaryText: {
    fontSize: 11,
    color: "#475569",
  },
  chatStatusPreviewCard: {
    position: "absolute",
    width: 236,
    backgroundColor: "#ffffff",
    borderWidth: 1,
    borderColor: "#cbd5e1",
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 7,
    gap: 4,
    shadowColor: "#000000",
    shadowOpacity: 0.14,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 3 },
    elevation: 5,
  },
  chatStatusPreviewTitle: {
    fontSize: 11,
    fontWeight: "700",
    color: "#334155",
  },
  chatStatusAuthRow: {
    marginTop: 2,
    borderWidth: 1,
    borderColor: "#e2e8f0",
    borderRadius: 7,
    backgroundColor: "#f8fafc",
    paddingHorizontal: 7,
    paddingVertical: 6,
    gap: 2,
  },
  chatStatusAuthLabel: {
    fontSize: 10,
    color: "#64748b",
    fontWeight: "700",
    letterSpacing: 0.2,
  },
  chatStatusAuthValue: {
    fontSize: 11,
    color: "#0f172a",
    fontWeight: "700",
  },
  chatStatusAuthErrorText: {
    fontSize: 10,
    lineHeight: 14,
    color: "#b91c1c",
  },
  chatStatusAuthSelectInlinePanel: {
    marginTop: 4,
    borderWidth: 1,
    borderColor: "#e2e8f0",
    borderRadius: 7,
    backgroundColor: "#ffffff",
    overflow: "hidden",
  },
  chatStatusAuthSelectInlineList: {
    maxHeight: 180,
  },
  chatStatusPreviewText: {
    fontSize: 10,
    lineHeight: 15,
    color: "#0f172a",
  },
  chatStatusAuthEmptyText: {
    fontSize: 12,
    color: "#64748b",
    paddingHorizontal: 10,
    paddingVertical: 10,
  },
  chatFooterSelectBackdrop: {
    flex: 1,
  },
  chatFooterSelectCard: {
    position: "absolute",
    backgroundColor: "#ffffff",
    borderWidth: 1,
    borderColor: "#cbd5e1",
    borderRadius: 8,
    paddingVertical: 4,
    shadowColor: "#000000",
    shadowOpacity: 0.14,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 3 },
    elevation: 5,
  },
  chatFooterSelectOption: {
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  chatFooterSelectOptionSelected: {
    backgroundColor: "#e2e8f0",
  },
  chatFooterSelectOptionText: {
    color: "#334155",
    fontSize: 12,
    fontWeight: "600",
  },
  chatFooterSelectOptionTextSelected: {
    color: "#0f172a",
  },
  chatThinkingPanel: {
    marginTop: 6,
    borderWidth: 1,
    borderColor: "#cbd5e1",
    borderRadius: 10,
    backgroundColor: "#f8fafc",
    paddingHorizontal: 10,
    paddingVertical: 8,
    gap: 4,
  },
  chatThinkingTitle: {
    color: "#334155",
    fontSize: 12,
    fontWeight: "800",
  },
  chatThinkingMessage: {
    color: "#0f172a",
    fontSize: 13,
    fontWeight: "600",
  },
  chatThinkingDetailText: {
    color: "#475569",
    fontSize: 11,
    lineHeight: 15,
  },
  chatThinkingElapsed: {
    color: "#475569",
    fontSize: 12,
    fontWeight: "700",
  },
  chatThinkingReloadButton: {
    alignSelf: "flex-start",
    borderWidth: 1,
    borderColor: "#cbd5e1",
    borderRadius: 8,
    backgroundColor: "#ffffff",
    paddingHorizontal: 8,
    paddingVertical: 4,
    marginTop: 2,
  },
  chatThinkingReloadButtonText: {
    color: "#334155",
    fontSize: 12,
    fontWeight: "700",
  },
  chatThinkingApprovalResumeButton: {
    borderColor: "#0f766e",
    backgroundColor: "#f0fdfa",
  },
  chatThinkingApprovalResumeButtonText: {
    color: "#0f766e",
    fontSize: 12,
    fontWeight: "800",
  },
  chatThinkingApprovalResumeHintText: {
    color: "#0f172a",
    fontSize: 11,
    lineHeight: 15,
  },
  chatThinkingToggle: {
    alignSelf: "flex-start",
    borderWidth: 1,
    borderColor: "#cbd5e1",
    borderRadius: 8,
    backgroundColor: "#ffffff",
    paddingHorizontal: 8,
    paddingVertical: 4,
    marginTop: 2,
  },
  chatThinkingToggleText: {
    color: "#334155",
    fontSize: 12,
    fontWeight: "700",
  },
  chatThinkingLogBox: {
    marginTop: 4,
    borderWidth: 1,
    borderColor: "#e2e8f0",
    borderRadius: 8,
    backgroundColor: "#ffffff",
    paddingHorizontal: 8,
    paddingVertical: 6,
    gap: 4,
  },
  chatThinkingLogLine: {
    color: "#475569",
    fontSize: 11,
    lineHeight: 15,
  },
  chatGeneratingInlineStatus: {
    marginTop: 2,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  chatGeneratingElapsedText: {
    color: "#8b8b84",
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "700",
  },
  chatComposerFullscreenRoot: {
    flex: 1,
    backgroundColor: "#ffffff",
    paddingHorizontal: 12,
    paddingTop: 8,
    paddingBottom: 12,
    gap: 8,
  },
  chatComposerFullscreenHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    minHeight: 40,
  },
  chatComposerFullscreenKeyboardAvoiding: {
    flex: 1,
    gap: 8,
  },
  chatComposerFullscreenTitle: {
    fontSize: 13,
    fontWeight: "700",
    color: "#334155",
  },
  chatComposerFullscreenClose: {
    width: 36,
    height: 36,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#cbd5e1",
    backgroundColor: "#ffffff",
    alignItems: "center",
    justifyContent: "center",
  },
  chatComposerFullscreenInputWrap: {
    flex: 1,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#cbd5e1",
    backgroundColor: "#ffffff",
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  chatComposerFullscreenInput: {
    flex: 1,
    minHeight: 200,
    borderWidth: 0,
    backgroundColor: "transparent",
    color: "#111827",
    fontSize: 15,
    paddingHorizontal: 0,
    paddingTop: 0,
    paddingBottom: 80,
    textAlignVertical: "top",
  },
} as const;
