import { createStylesByTheme, type VisualTheme } from "../theme/visualThemes";

export function createChatComposerStyles(theme: VisualTheme) {
  return {
  chatComposer: {
    position: "relative",
    gap: 8,
    paddingTop: 8,
    borderTopWidth: theme.borders.thin,
    borderTopColor: theme.colors.borderSubtle,
  },
  connectionStatusArea: {
    position: "absolute",
    right: 0,
    top: -36,
    zIndex: 20,
    elevation: 20,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  chatScrollControls: {
    flexDirection: "row",
    gap: 4,
  },
  chatScrollControlButton: {
    width: 26,
    height: 26,
    borderRadius: 8,
    borderWidth: theme.borders.thin,
    borderColor: theme.colors.borderSubtle,
    backgroundColor: theme.colors.surfaceTranslucent,
    alignItems: "center",
    justifyContent: "center",
  },
  chatInputWrapper: {
    flexDirection: "row",
    alignItems: "flex-end",
    gap: 8,
    borderRadius: 12,
    borderWidth: theme.borders.thin,
    borderColor: theme.colors.border,
    backgroundColor: theme.colors.surface,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  chatInput: {
    minHeight: 44,
    maxHeight: 160,
    borderRadius: 0,
    borderWidth: 0,
    borderColor: "transparent",
    backgroundColor: "transparent",
    color: theme.colors.controlTextPrimary,
    fontSize: theme.typography.input.fontSize,
    paddingHorizontal: 0,
    paddingVertical: 0,
  },
  chatComposerInput: {
    flex: 1,
  },
  chatComposerInputArea: {
    flex: 1,
    minWidth: 0,
    position: "relative",
  },
  chatComposerInputWithExpandButton: {
    // paddingではなくmarginで空ける: TextInput(NSTextView)のフレームがボタンの
    // 下まで伸びていると、macOSではクリックが選択トラッキングに飲まれる。
    marginRight: 34,
  },
  chatComposerExpandButton: {
    position: "absolute",
    right: 0,
    top: 0,
    width: 28,
    height: 28,
    borderRadius: 8,
    borderWidth: theme.borders.thin,
    borderColor: theme.colors.border,
    backgroundColor: theme.colors.surface,
    alignItems: "center",
    justifyContent: "center",
  },
  chatWaveformBox: {
    flex: 1,
    marginTop: 0,
    marginBottom: 0,
    height: 54,
    paddingHorizontal: 0,
    paddingVertical: 0,
    borderWidth: 0,
  },
  chatDirectSttBox: {
    flex: 1,
    minHeight: 54,
    maxHeight: 108,
    borderRadius: 8,
    borderWidth: theme.borders.thin,
    borderColor: theme.colors.borderSubtle,
    backgroundColor: theme.colors.surfaceRaised,
    paddingHorizontal: 10,
    paddingVertical: 6,
    gap: 4,
    justifyContent: "center",
  },
  chatDirectSttLabel: {
    fontSize: theme.typography.micro.fontSize,
    fontWeight: "700",
    color: theme.colors.textMuted,
    textTransform: "uppercase",
    letterSpacing: 0.3,
  },
  chatDirectSttText: {
    fontSize: theme.typography.body.fontSize,
    lineHeight: theme.typography.body.lineHeight,
    color: theme.colors.textPrimary,
  },
  chatComposerIconRow: {
    flexDirection: "row",
    gap: 8,
    justifyContent: "flex-end",
    alignSelf: "flex-end",
  },
  chatAbButton: {
    minWidth: 56,
    height: 42,
    borderRadius: 12,
    borderWidth: theme.borders.thin,
    borderColor: theme.colors.border,
    backgroundColor: theme.colors.surface,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 8,
  },
  chatAbButtonActive: {
    borderColor: theme.tones.danger.border,
    backgroundColor: theme.tones.danger.background,
  },
  chatAbButtonText: {
    color: theme.colors.textSecondary,
    fontSize: theme.typography.small.fontSize,
    fontWeight: "800",
    letterSpacing: 0.2,
  },
  chatAbButtonTextActive: {
    color: theme.colors.dangerTextStrong,
  },
  chatIconButton: {
    width: 42,
    height: 42,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: theme.borders.thin,
  },
  chatRecordIconButton: {
    backgroundColor: theme.colors.textSecondary,
    borderColor: theme.colors.textSecondary,
  },
  chatFaceTrackIconButton: {
    backgroundColor: theme.colors.surfaceMuted,
    borderColor: theme.colors.border,
  },
  chatFaceTrackIconButtonEnabled: {
    backgroundColor: theme.tones.success.background,
    borderColor: theme.colors.positiveText,
  },
  chatFaceTrackIconButtonBlocked: {
    backgroundColor: theme.tones.warning.background,
    borderColor: theme.colors.warningBorderStrong,
  },
  chatFaceTrackIconButtonIdle: {
    backgroundColor: theme.colors.surfaceRaised,
    borderColor: theme.colors.borderStrong,
  },
  chatSlashIconButton: {
    backgroundColor: theme.colors.surface,
    borderColor: theme.colors.border,
  },
  chatSlashIconText: {
    color: theme.colors.textSecondary,
    fontSize: theme.typography.title.fontSize,
    fontWeight: "800",
    marginTop: -1,
  },
  chatActionRow: {
    flexDirection: "row",
    gap: 8,
  },
  chatPrimaryButton: {
    flex: 1,
    borderRadius: 10,
    backgroundColor: theme.colors.primaryAction,
    paddingVertical: 11,
    alignItems: "center",
  },
  chatSecondaryButton: {
    flex: 1,
    borderRadius: 10,
    backgroundColor: theme.colors.textSecondary,
    paddingVertical: 11,
    alignItems: "center",
  },
  chatButtonText: {
    color: theme.colors.textOnAccent,
    fontSize: theme.typography.body.fontSize,
    fontWeight: "700",
  },
  chatHint: {
    color: theme.colors.textMuted,
    fontSize: theme.typography.small.fontSize,
  },
  chatFooterSettingsRow: {
    marginTop: 2,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 2,
    position: "relative",
  },
  chatFooterSettingsInline: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
    gap: 8,
  },
  chatFooterSettingsText: {
    fontSize: theme.typography.small.fontSize,
    color: theme.tones.neutral.foreground,
    textDecorationLine: "underline",
  },
  chatThreadStatusCenter: {
    position: "absolute",
    left: 84,
    right: 84,
    alignItems: "center",
  },
  chatThreadStatusText: {
    color: theme.colors.textMuted,
    fontSize: theme.typography.caption.fontSize,
  },
  chatStatusSummaryText: {
    fontSize: theme.typography.caption.fontSize,
    color: theme.tones.neutral.foreground,
  },
  chatStatusPreviewCard: {
    position: "absolute",
    backgroundColor: theme.colors.surface,
    borderWidth: theme.borders.thin,
    borderColor: theme.colors.border,
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 7,
    gap: 4,
    shadowColor: theme.colors.shadow,
    shadowOpacity: 0.14,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 3 },
    elevation: 5,
  },
  chatStatusPreviewTitle: {
    fontSize: theme.typography.caption.fontSize,
    fontWeight: "700",
    color: theme.colors.textSecondary,
  },
  chatStatusAuthRow: {
    marginTop: 2,
    borderWidth: theme.borders.thin,
    borderColor: theme.colors.borderSubtle,
    borderRadius: 7,
    backgroundColor: theme.colors.surfaceRaised,
    paddingHorizontal: 7,
    paddingVertical: 6,
    gap: 2,
  },
  chatStatusAuthLabel: {
    fontSize: theme.typography.micro.fontSize,
    color: theme.colors.textMuted,
    fontWeight: "700",
    letterSpacing: 0.2,
  },
  chatStatusAuthValue: {
    fontSize: theme.typography.caption.fontSize,
    color: theme.colors.textPrimary,
    fontWeight: "700",
  },
  chatStatusAuthErrorText: {
    fontSize: theme.typography.micro.fontSize,
    lineHeight: theme.typography.micro.lineHeight,
    color: theme.tones.danger.foreground,
  },
  chatStatusAuthSelectInlinePanel: {
    marginTop: 4,
    borderWidth: theme.borders.thin,
    borderColor: theme.colors.borderSubtle,
    borderRadius: 7,
    backgroundColor: theme.colors.surface,
    overflow: "hidden",
  },
  chatStatusAuthSelectInlineList: {
    maxHeight: 180,
  },
  chatStatusAuthOptionLimits: {
    color: theme.tones.neutral.foreground,
    fontSize: theme.typography.caption.fontSize,
    lineHeight: theme.typography.caption.lineHeight,
  },
  chatStatusPreviewText: {
    fontSize: theme.typography.micro.fontSize,
    lineHeight: theme.typography.micro.lineHeight,
    color: theme.colors.textPrimary,
  },
  chatStatusAuthEmptyText: {
    fontSize: theme.typography.small.fontSize,
    color: theme.colors.textMuted,
    paddingHorizontal: 10,
    paddingVertical: 10,
  },
  chatFooterSelectBackdrop: {
    flex: 1,
  },
  chatFooterSelectCard: {
    position: "absolute",
    backgroundColor: theme.colors.surface,
    borderWidth: theme.borders.thin,
    borderColor: theme.colors.border,
    borderRadius: 8,
    paddingVertical: 4,
    shadowColor: theme.colors.shadow,
    shadowOpacity: 0.14,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 3 },
    elevation: 5,
  },
  chatFooterSelectOption: {
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  chatFooterSelectOptionSelected: {
    backgroundColor: theme.colors.surfaceSubtle,
  },
  chatFooterSelectOptionText: {
    color: theme.colors.textSecondary,
    fontSize: theme.typography.small.fontSize,
    fontWeight: "600",
  },
  chatFooterSelectOptionTextSelected: {
    color: theme.colors.textPrimary,
  },
  chatThinkingPanel: {
    marginTop: 6,
    borderWidth: theme.borders.thin,
    borderColor: theme.colors.border,
    borderRadius: 10,
    backgroundColor: theme.colors.surfaceRaised,
    paddingHorizontal: 10,
    paddingVertical: 8,
    gap: 4,
  },
  chatThinkingTitle: {
    color: theme.colors.textSecondary,
    fontSize: theme.typography.small.fontSize,
    fontWeight: "800",
  },
  chatThinkingMessage: {
    color: theme.colors.textPrimary,
    fontSize: theme.typography.compact.fontSize,
    fontWeight: "600",
  },
  chatThinkingDetailText: {
    color: theme.tones.neutral.foreground,
    fontSize: theme.typography.caption.fontSize,
    lineHeight: theme.typography.caption.lineHeight,
  },
  chatThinkingElapsed: {
    color: theme.tones.neutral.foreground,
    fontSize: theme.typography.small.fontSize,
    fontWeight: "700",
  },
  chatThinkingReloadButton: {
    alignSelf: "flex-start",
    borderWidth: theme.borders.thin,
    borderColor: theme.colors.border,
    borderRadius: 8,
    backgroundColor: theme.colors.surface,
    paddingHorizontal: 8,
    paddingVertical: 4,
    marginTop: 2,
  },
  chatThinkingReloadButtonText: {
    color: theme.colors.textSecondary,
    fontSize: theme.typography.small.fontSize,
    fontWeight: "700",
  },
  chatThinkingApprovalResumeButton: {
    borderColor: theme.colors.primaryActionStrong,
    backgroundColor: theme.colors.surfaceActionSoft,
  },
  chatThinkingApprovalResumeButtonText: {
    color: theme.colors.primaryActionStrong,
    fontSize: theme.typography.small.fontSize,
    fontWeight: "800",
  },
  chatThinkingApprovalResumeHintText: {
    color: theme.colors.textPrimary,
    fontSize: theme.typography.caption.fontSize,
    lineHeight: theme.typography.caption.lineHeight,
  },
  chatThinkingToggle: {
    alignSelf: "flex-start",
    borderWidth: theme.borders.thin,
    borderColor: theme.colors.border,
    borderRadius: 8,
    backgroundColor: theme.colors.surface,
    paddingHorizontal: 8,
    paddingVertical: 4,
    marginTop: 2,
  },
  chatThinkingToggleText: {
    color: theme.colors.textSecondary,
    fontSize: theme.typography.small.fontSize,
    fontWeight: "700",
  },
  chatThinkingLogBox: {
    marginTop: 4,
    borderWidth: theme.borders.thin,
    borderColor: theme.colors.borderSubtle,
    borderRadius: 8,
    backgroundColor: theme.colors.surface,
    paddingHorizontal: 8,
    paddingVertical: 6,
    gap: 4,
  },
  chatThinkingLogLine: {
    color: theme.tones.neutral.foreground,
    fontSize: theme.typography.caption.fontSize,
    lineHeight: theme.typography.caption.lineHeight,
  },
  chatGeneratingInlineStatus: {
    marginTop: 2,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  chatGeneratingElapsedText: {
    color: theme.colors.textWarmMuted,
    fontSize: theme.typography.small.fontSize,
    lineHeight: theme.typography.small.lineHeight,
    fontWeight: "700",
  },
  } as const;
}

export const chatComposerStylesByTheme = createStylesByTheme(createChatComposerStyles);
