export const debugBaseStyles = {
  debugHeaderRow: {
    marginBottom: 4,
    flexDirection: "row",
    gap: 8,
  },
  debugBackButton: {
    backgroundColor: "#e2e8f0",
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  debugBackButtonText: {
    color: "#1e293b",
    fontSize: 12,
    fontWeight: "700",
  },
  debugLabButton: {
    backgroundColor: "#0f766e",
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  debugLabButtonText: {
    color: "#ecfeff",
    fontSize: 12,
    fontWeight: "700",
  },
  errorText: {
    color: "#b91c1c",
    fontSize: 13,
    fontWeight: "600",
  },
  title: {
    fontSize: 24,
    fontWeight: "700",
    color: "#111827",
    marginBottom: 8,
  },
  label: {
    fontSize: 13,
    fontWeight: "600",
    color: "#374151",
    marginTop: 8,
  },
  input: {
    backgroundColor: "#ffffff",
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#d1d5db",
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 15,
    color: "#111827",
  },
  selectButton: {
    backgroundColor: "#ffffff",
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#d1d5db",
    paddingHorizontal: 12,
    paddingVertical: 12,
  },
  selectButtonText: {
    color: "#111827",
    fontSize: 15,
  },
  multiline: {
    minHeight: 120,
  },
  multilineSmall: {
    minHeight: 72,
  },
  button: {
    marginTop: 12,
    backgroundColor: "#0f766e",
    borderRadius: 10,
    paddingVertical: 12,
    alignItems: "center",
  },
  buttonSecondary: {
    flex: 1,
    backgroundColor: "#334155",
    borderRadius: 10,
    paddingVertical: 12,
    alignItems: "center",
  },
  buttonDanger: {
    backgroundColor: "#b91c1c",
  },
  row: {
    marginTop: 4,
    flexDirection: "row",
    gap: 8,
  },
  providerRow: {
    marginTop: 4,
    flexDirection: "row",
    gap: 8,
  },
  speedRow: {
    marginTop: 4,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  speedButton: {
    width: 48,
    backgroundColor: "#334155",
    borderRadius: 10,
    paddingVertical: 10,
    alignItems: "center",
  },
  speedInput: {
    flex: 1,
    textAlign: "center",
  },
  providerButton: {
    flex: 1,
    borderWidth: 1,
    borderColor: "#d1d5db",
    backgroundColor: "#ffffff",
    borderRadius: 10,
    alignItems: "center",
    paddingVertical: 10,
  },
  providerButtonSelected: {
    backgroundColor: "#0f766e",
    borderColor: "#0f766e",
  },
  providerButtonText: {
    fontSize: 14,
    fontWeight: "700",
    color: "#111827",
  },
  providerButtonTextSelected: {
    color: "#ffffff",
  },
  buttonDisabled: {
    opacity: 0.5,
  },
  buttonText: {
    color: "#ffffff",
    fontSize: 15,
    fontWeight: "700",
  },
  hint: {
    color: "#6b7280",
    fontSize: 12,
    marginTop: 2,
  },
  switchRow: {
    marginTop: 6,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: "#ffffff",
    borderWidth: 1,
    borderColor: "#d1d5db",
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  switchLabel: {
    fontSize: 13,
    color: "#111827",
    fontWeight: "600",
  },
  debugVariantButton: {
    minWidth: 42,
    borderWidth: 1,
    borderColor: "#d1d5db",
    borderRadius: 10,
    backgroundColor: "#ffffff",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  debugVariantButtonActive: {
    borderColor: "#b91c1c",
    backgroundColor: "#fee2e2",
  },
  debugVariantButtonText: {
    color: "#334155",
    fontSize: 13,
    fontWeight: "800",
  },
  debugVariantButtonTextActive: {
    color: "#991b1b",
  },
  clearButton: {
    alignSelf: "flex-start",
    marginTop: 4,
    backgroundColor: "#e5e7eb",
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  clearButtonText: {
    color: "#111827",
    fontSize: 12,
    fontWeight: "600",
  },
} as const;
