export const llmDebugStyles = {
  llmStatusCard: {
    marginTop: 6,
    borderWidth: 1,
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 8,
    gap: 6,
  },
  llmStatusHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  llmStatusBadge: {
    flexDirection: "row",
    alignItems: "center",
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 4,
    gap: 6,
  },
  llmStatusIcon: {
    fontSize: 12,
    color: "#111827",
    fontWeight: "800",
    minWidth: 10,
    textAlign: "center",
  },
  llmStatusLottieWrap: {
    width: 32,
    height: 32,
    alignItems: "center",
    justifyContent: "center",
  },
  llmStatusLottie: {
    width: 32,
    height: 32,
    borderRadius: 999,
    overflow: "hidden",
  },
  llmStatusBadgeText: {
    fontSize: 12,
    fontWeight: "800",
    letterSpacing: 0.2,
  },
  llmStatusElapsed: {
    fontSize: 12,
    fontWeight: "700",
  },
  llmStatusDetail: {
    fontSize: 13,
    fontWeight: "600",
  },
  llmMetaRow: {
    flexDirection: "row",
    gap: 6,
    flexWrap: "wrap",
  },
  llmMetaChip: {
    fontSize: 11,
    color: "#374151",
    backgroundColor: "#ffffff",
    borderWidth: 1,
    borderColor: "#d1d5db",
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  llmSummaryText: {
    fontSize: 11,
    color: "#4b5563",
    lineHeight: 14,
  },
  streamList: {
    marginTop: 4,
    borderWidth: 1,
    borderColor: "#d1d5db",
    borderRadius: 10,
    backgroundColor: "#ffffff",
    padding: 8,
    gap: 6,
  },
  streamItem: {
    borderBottomWidth: 1,
    borderBottomColor: "#f1f5f9",
    paddingBottom: 6,
  },
  streamStatus: {
    color: "#0f766e",
    fontSize: 12,
    fontWeight: "700",
  },
  streamText: {
    color: "#374151",
    fontSize: 12,
    marginTop: 2,
  },
  replyBox: {
    marginTop: 4,
    backgroundColor: "#ffffff",
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#d1d5db",
    padding: 12,
    minHeight: 100,
  },
  replyText: {
    color: "#111827",
    fontSize: 16,
    lineHeight: 24,
  },
} as const;
