import { Platform, StyleSheet } from "react-native";

const YOUTUBE_INLINE_PLAYER_HEIGHT = 220;

export const mediaModalStyles = {
  youtubeList: {
    marginTop: 4,
    gap: 8,
  },
  youtubeCard: {
    backgroundColor: "#ffffff",
    borderWidth: 1,
    borderColor: "#d1d5db",
    borderRadius: 10,
    overflow: "hidden",
  },
  youtubeCardTouchable: {
    width: "100%",
  },
  youtubeThumb: {
    width: "100%",
    height: 180,
    backgroundColor: "#0f172a",
  },
  youtubeMeta: {
    padding: 10,
    gap: 4,
  },
  youtubeTitle: {
    fontSize: 13,
    fontWeight: "700",
    color: "#111827",
  },
  youtubeSub: {
    fontSize: 12,
    color: "#475569",
  },
  youtubePlayerInline: {
    marginTop: 0,
    height: YOUTUBE_INLINE_PLAYER_HEIGHT,
    borderRadius: 10,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "#d1d5db",
    backgroundColor: "#0f172a",
  },
  youtubePlayerInlinePlaceholder: {
    marginTop: 0,
    height: YOUTUBE_INLINE_PLAYER_HEIGHT,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#d1d5db",
    backgroundColor: "#e2e8f0",
    alignItems: "center",
    justifyContent: "center",
  },
  youtubePlayerInlinePlaceholderText: {
    fontSize: 12,
    color: "#334155",
    fontWeight: "600",
  },
  youtubeOverlayWrap: {
    ...StyleSheet.absoluteFillObject,
    position: "absolute",
  },
  chatBottomToastWrap: {
    position: "absolute",
    left: 12,
    right: 12,
    bottom: 110,
    zIndex: 6,
    elevation: 16,
  },
  chatBottomToast: {
    borderRadius: 12,
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 8,
    backgroundColor: "#ffffff",
    shadowColor: "#0f172a",
    shadowOpacity: 0.18,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 3 },
  },
  chatBottomToastUser: {
    borderColor: "#0f766e",
    backgroundColor: "#f0fdfa",
  },
  chatBottomToastAssistant: {
    borderColor: "#2563eb",
    backgroundColor: "#eff6ff",
  },
  chatBottomToastRole: {
    fontSize: 10,
    fontWeight: "800",
    letterSpacing: 0.3,
    color: "#334155",
    marginBottom: 2,
  },
  chatBottomToastText: {
    color: "#0f172a",
    fontSize: 12,
    lineHeight: 16,
  },
  youtubeFloatingContainer: {
    position: "absolute",
    left: 0,
    top: 0,
    width: 176,
    height: 110,
    zIndex: 4,
    elevation: 8,
  },
  youtubeFloatingCloseButton: {
    position: "absolute",
    right: 4,
    top: 4,
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: "rgba(15, 23, 42, 0.92)",
    borderWidth: 1,
    borderColor: "#475569",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 3,
    elevation: 12,
  },
  youtubeInlineOverlayPlayer: {
    position: "absolute",
    top: 0,
    borderRadius: 10,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "#d1d5db",
    backgroundColor: "#0f172a",
  },
  youtubeFloatingPlayer: {
    width: "100%",
    height: "100%",
    borderRadius: 12,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "#334155",
    backgroundColor: "#020617",
    shadowColor: "#0f172a",
    shadowOpacity: 0.32,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 8,
  },
  youtubeFloatingGestureLayer: {
    ...StyleSheet.absoluteFillObject,
    borderRadius: 12,
    zIndex: 2,
  },
  youtubeFloatingControlOutline: {
    ...StyleSheet.absoluteFillObject,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: "#60a5fa",
    zIndex: 3,
  },
  youtubeWebView: {
    flex: 1,
    backgroundColor: "#0f172a",
  },
  historyItem: {
    marginTop: 6,
    backgroundColor: "#ffffff",
    borderWidth: 1,
    borderColor: "#d1d5db",
    borderRadius: 10,
    padding: 10,
    width: "100%",
    maxWidth: "100%",
  },
  historyTime: {
    fontSize: 12,
    color: "#6b7280",
    marginBottom: 4,
  },
  historyBody: {
    fontSize: 14,
    color: "#111827",
    lineHeight: 20,
    flexShrink: 1,
  },
  voiceList: {
    marginTop: 6,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#d1d5db",
    backgroundColor: "#ffffff",
    maxHeight: 220,
    overflow: "hidden",
  },
  voiceListScroll: {
    maxHeight: 220,
  },
  voiceItem: {
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: "#f1f5f9",
  },
  voiceItemSelected: {
    backgroundColor: "#ecfeff",
  },
  voiceName: {
    fontSize: 14,
    color: "#111827",
    fontWeight: "600",
  },
  voiceMeta: {
    marginTop: 2,
    fontSize: 12,
    color: "#6b7280",
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: "rgba(17,24,39,0.45)",
    justifyContent: "center",
    padding: 20,
  },
  directoryExplorerBackdrop: {
    flex: 1,
    backgroundColor: "rgba(15,23,42,0.42)",
    justifyContent: "flex-start",
    paddingHorizontal: 14,
    paddingTop: 34,
    paddingBottom: 14,
  },
  directoryExplorerCard: {
    flex: 1,
    borderRadius: 18,
    backgroundColor: "#f8fafc",
    borderWidth: 1,
    borderColor: "#dbeafe",
    overflow: "hidden",
    shadowColor: "#0f172a",
    shadowOpacity: 0.2,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
    elevation: 12,
  },
  directoryExplorerHeader: {
    paddingHorizontal: 14,
    paddingTop: 14,
    paddingBottom: 10,
    gap: 6,
    borderBottomWidth: 1,
    borderBottomColor: "#dbeafe",
    backgroundColor: "#eff6ff",
  },
  directoryExplorerHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
  },
  directoryExplorerCloseButton: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: "center",
    justifyContent: "center",
  },
  directoryExplorerCurrentPathText: {
    fontSize: 12,
    lineHeight: 18,
    color: "#1e293b",
  },
  directoryExplorerListArea: {
    flex: 1,
    paddingHorizontal: 14,
    paddingTop: 10,
    paddingBottom: 10,
    gap: 8,
  },
  directoryExplorerLoadingRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  directoryExplorerListScroll: {
    flex: 1,
  },
  directoryExplorerListContent: {
    gap: 8,
    paddingBottom: 4,
  },
  directoryExplorerEmptyState: {
    minHeight: 120,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#e2e8f0",
    backgroundColor: "#ffffff",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
  },
  directoryExplorerEntryButton: {
    minHeight: 62,
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 8,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  directoryExplorerEntryMain: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  directoryExplorerEntryTextWrap: {
    flex: 1,
    gap: 2,
  },
  directoryExplorerEntryName: {
    fontSize: 14,
    color: "#0f172a",
    fontWeight: "600",
  },
  directoryExplorerFooter: {
    paddingHorizontal: 14,
    paddingTop: 10,
    paddingBottom: 14,
    gap: 8,
    borderTopWidth: 1,
    borderTopColor: "#dbeafe",
    backgroundColor: "#ffffff",
  },
  directoryExplorerNavRow: {
    flexDirection: "row",
    gap: 8,
  },
  directoryExplorerSecondaryButton: {
    flex: 1,
    minHeight: 42,
    borderRadius: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
  },
  directoryExplorerSecondaryButtonText: {
    fontSize: 14,
    color: "#1e40af",
    fontWeight: "700",
  },
  directoryExplorerPrimaryButton: {
    minHeight: 46,
    borderRadius: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  directoryExplorerPrimaryButtonText: {
    fontSize: 15,
    color: "#1e40af",
    fontWeight: "700",
  },
  modalCard: {
    borderRadius: 12,
    backgroundColor: "#ffffff",
    borderWidth: 1,
    borderColor: "#e5e7eb",
    padding: 10,
    gap: 8,
  },
  modalCardLarge: {
    borderRadius: 12,
    backgroundColor: "#ffffff",
    borderWidth: 1,
    borderColor: "#e5e7eb",
    padding: 10,
    gap: 8,
    maxHeight: "86%",
  },
  modalTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: "#111827",
    marginBottom: 4,
  },
  modalOption: {
    borderWidth: 1,
    borderColor: "#e5e7eb",
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 10,
  },
  modalOptionSelected: {
    borderColor: "#0f766e",
    backgroundColor: "#ecfeff",
  },
  modalOptionText: {
    fontSize: 14,
    color: "#111827",
    fontWeight: "600",
  },
  modalOptionPrimaryRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  modalOptionPrimaryText: {
    flex: 1,
    fontSize: 14,
    color: "#111827",
    fontWeight: "600",
  },
  modalOptionContextPct: {
    fontSize: 13,
    color: "#0f766e",
    fontWeight: "700",
    textAlign: "right",
    minWidth: 44,
  },
  modalOptionTextSelected: {
    color: "#0f766e",
  },
  modalOptionSubText: {
    marginTop: 2,
    fontSize: 12,
    color: "#6b7280",
  },
  modalListScroll: {
    maxHeight: 360,
  },
  approvalBackdrop: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    padding: 24,
    backgroundColor: "rgba(0, 0, 0, 0.28)",
  },
  approvalModalCard: {
    width: "100%",
    maxWidth: 286,
    borderRadius: 14,
    backgroundColor: "rgba(242, 242, 247, 0.96)",
    overflow: "hidden",
    shadowColor: "#000000",
    shadowOpacity: 0.2,
    shadowRadius: 22,
    shadowOffset: { width: 0, height: 10 },
    elevation: 18,
  },
  approvalAlertBody: {
    paddingTop: 18,
    paddingHorizontal: 18,
    paddingBottom: 15,
    alignItems: "center",
  },
  approvalModalTitle: {
    marginBottom: 6,
    fontSize: 17,
    lineHeight: 21,
    fontWeight: "600",
    color: "#000000",
    textAlign: "center",
  },
  approvalSessionContextText: {
    alignSelf: "stretch",
    marginBottom: 7,
    fontSize: 11,
    lineHeight: 14,
    color: "rgba(60,60,67,0.62)",
    textAlign: "center",
  },
  approvalMessageText: {
    fontSize: 13,
    lineHeight: 18,
    color: "rgba(0,0,0,0.78)",
    textAlign: "center",
  },
  approvalCommandText: {
    alignSelf: "stretch",
    marginTop: 11,
    borderRadius: 8,
    backgroundColor: "rgba(118,118,128,0.12)",
    paddingHorizontal: 9,
    paddingVertical: 8,
    fontSize: 12,
    lineHeight: 16,
    color: "rgba(0,0,0,0.78)",
    textAlign: "left",
    fontFamily: Platform.select({ ios: "Menlo", android: "monospace", default: "monospace" }),
  },
  approvalActionList: {
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: "rgba(60,60,67,0.24)",
  },
  approvalAlertButton: {
    minHeight: 44,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: "rgba(60,60,67,0.24)",
    backgroundColor: "rgba(255,255,255,0.18)",
  },
  approvalAlertButtonPrimary: {
    borderTopWidth: 0,
  },
  approvalAlertButtonText: {
    fontSize: 17,
    lineHeight: 21,
    color: "#007aff",
    textAlign: "center",
  },
  approvalAlertButtonPrimaryText: {
    fontWeight: "600",
  },
  approvalAlertButtonDangerText: {
    color: "#ff3b30",
  },
} as const;
