import { Platform, StyleSheet } from "react-native";
import { createStylesByTheme, type VisualTheme } from "../theme/visualThemes";

const YOUTUBE_INLINE_PLAYER_HEIGHT = 220;

export function createMediaModalStyles(theme: VisualTheme) {
  return {
  youtubeList: {
    marginTop: 4,
    gap: 8,
  },
  youtubeCard: {
    backgroundColor: theme.colors.surface,
    borderWidth: theme.borders.thin,
    borderColor: theme.colors.groupedBorder,
    borderRadius: 10,
    overflow: "hidden",
  },
  youtubeCardTouchable: {
    width: "100%",
  },
  youtubeThumb: {
    width: "100%",
    height: 180,
    backgroundColor: theme.dark.surface,
  },
  youtubeMeta: {
    padding: 10,
    gap: 4,
  },
  youtubeTitle: {
    fontSize: theme.typography.compact.fontSize,
    fontWeight: "700",
    color: theme.colors.controlTextPrimary,
  },
  youtubeSub: {
    fontSize: theme.typography.small.fontSize,
    color: theme.colors.textMuted,
  },
  youtubePlayerInline: {
    marginTop: 0,
    height: YOUTUBE_INLINE_PLAYER_HEIGHT,
    borderRadius: 10,
    overflow: "hidden",
    borderWidth: theme.borders.thin,
    borderColor: theme.colors.groupedBorder,
    backgroundColor: theme.dark.surface,
  },
  youtubePlayerInlinePlaceholder: {
    marginTop: 0,
    height: YOUTUBE_INLINE_PLAYER_HEIGHT,
    borderRadius: 10,
    borderWidth: theme.borders.thin,
    borderColor: theme.colors.groupedBorder,
    backgroundColor: theme.colors.surfaceSubtle,
    alignItems: "center",
    justifyContent: "center",
  },
  youtubePlayerInlinePlaceholderText: {
    fontSize: theme.typography.small.fontSize,
    color: theme.colors.textSecondary,
    fontWeight: "600",
  },
  youtubeOverlayWrap: {
    ...StyleSheet.absoluteFillObject,
    position: "absolute",
  },
  chatBottomToastWrap: {
    position: "absolute",
    left: 12,
    right: 12,
    bottom: 110,
    zIndex: 6,
    elevation: 16,
  },
  chatBottomToast: {
    borderRadius: 12,
    borderWidth: theme.borders.thin,
    paddingHorizontal: 10,
    paddingVertical: 8,
    backgroundColor: theme.colors.surface,
    shadowColor: theme.colors.textPrimary,
    shadowOpacity: 0.18,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 3 },
  },
  chatBottomToastUser: {
    borderColor: theme.colors.primaryAction,
    backgroundColor: theme.colors.surfaceActionSoft,
  },
  chatBottomToastAssistant: {
    borderColor: theme.colors.accent,
    backgroundColor: theme.colors.surfaceSelected,
  },
  chatBottomToastRole: {
    fontSize: theme.typography.micro.fontSize,
    fontWeight: "800",
    letterSpacing: 0.3,
    color: theme.colors.textSecondary,
    marginBottom: 2,
  },
  chatBottomToastText: {
    color: theme.colors.textPrimary,
    fontSize: theme.typography.small.fontSize,
    lineHeight: theme.typography.captionRelaxed.lineHeight,
  },
  youtubeFloatingContainer: {
    position: "absolute",
    left: 0,
    top: 0,
    width: 176,
    height: 110,
    zIndex: 4,
    elevation: 8,
  },
  youtubeFloatingCloseButton: {
    position: "absolute",
    right: 4,
    top: 4,
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: theme.colors.mediaScrim,
    borderWidth: theme.borders.thin,
    borderColor: theme.colors.textMuted,
    alignItems: "center",
    justifyContent: "center",
    zIndex: 3,
    elevation: 12,
  },
  youtubeInlineOverlayPlayer: {
    position: "absolute",
    top: 0,
    borderRadius: 10,
    overflow: "hidden",
    borderWidth: theme.borders.thin,
    borderColor: theme.colors.groupedBorder,
    backgroundColor: theme.dark.surface,
  },
  youtubeFloatingPlayer: {
    width: "100%",
    height: "100%",
    borderRadius: 12,
    overflow: "hidden",
    borderWidth: theme.borders.thin,
    borderColor: theme.dark.border,
    backgroundColor: theme.dark.canvas,
    shadowColor: theme.dark.surface,
    shadowOpacity: 0.32,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 8,
  },
  youtubeFloatingGestureLayer: {
    ...StyleSheet.absoluteFillObject,
    borderRadius: 12,
    zIndex: 2,
  },
  youtubeFloatingControlOutline: {
    ...StyleSheet.absoluteFillObject,
    borderRadius: 12,
    borderWidth: theme.borders.strong,
    borderColor: theme.colors.floatingFocus,
    zIndex: 3,
  },
  youtubeWebView: {
    flex: 1,
    backgroundColor: theme.dark.surface,
  },
  historyItem: {
    marginTop: 6,
    backgroundColor: theme.colors.surface,
    borderWidth: theme.borders.thin,
    borderColor: theme.colors.groupedBorder,
    borderRadius: 10,
    padding: 10,
    width: "100%",
    maxWidth: "100%",
  },
  historyTime: {
    fontSize: theme.typography.small.fontSize,
    color: theme.colors.textSubtle,
    marginBottom: 4,
  },
  historyBody: {
    fontSize: theme.typography.body.fontSize,
    color: theme.colors.controlTextPrimary,
    lineHeight: theme.typography.body.lineHeight,
    flexShrink: 1,
  },
  voiceList: {
    marginTop: 6,
    borderRadius: 10,
    borderWidth: theme.borders.thin,
    borderColor: theme.colors.groupedBorder,
    backgroundColor: theme.colors.surface,
    maxHeight: 220,
    overflow: "hidden",
  },
  voiceListScroll: {
    maxHeight: 220,
  },
  voiceItem: {
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderBottomWidth: theme.borders.thin,
    borderBottomColor: theme.colors.surfaceMuted,
  },
  voiceItemSelected: {
    backgroundColor: theme.colors.surfaceActionSelected,
  },
  voiceName: {
    fontSize: theme.typography.body.fontSize,
    color: theme.colors.controlTextPrimary,
    fontWeight: "600",
  },
  voiceMeta: {
    marginTop: 2,
    fontSize: theme.typography.small.fontSize,
    color: theme.colors.textSubtle,
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: theme.colors.controlBackdropStrong,
    justifyContent: "center",
    padding: 20,
  },
  directoryExplorerBackdrop: {
    flex: 1,
    backgroundColor: theme.colors.directoryBackdrop,
    justifyContent: "flex-start",
    paddingHorizontal: 14,
    paddingTop: 34,
    paddingBottom: 14,
  },
  directoryExplorerCard: {
    flex: 1,
    borderRadius: 18,
    backgroundColor: theme.colors.surfaceRaised,
    borderWidth: theme.borders.thin,
    borderColor: theme.colors.borderInfo,
    overflow: "hidden",
    shadowColor: theme.colors.textPrimary,
    shadowOpacity: 0.2,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
    elevation: 12,
  },
  directoryExplorerHeader: {
    paddingHorizontal: 14,
    paddingTop: 14,
    paddingBottom: 10,
    gap: 6,
    borderBottomWidth: theme.borders.thin,
    borderBottomColor: theme.colors.borderInfo,
    backgroundColor: theme.colors.surfaceSelected,
  },
  directoryExplorerHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
  },
  directoryExplorerCloseButton: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: "center",
    justifyContent: "center",
  },
  directoryExplorerCurrentPathText: {
    fontSize: theme.typography.small.fontSize,
    lineHeight: theme.typography.compact.lineHeight,
    color: theme.colors.textStrong,
  },
  directoryExplorerListArea: {
    flex: 1,
    paddingHorizontal: 14,
    paddingTop: 10,
    paddingBottom: 10,
    gap: 8,
  },
  directoryExplorerLoadingRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  directoryExplorerListScroll: {
    flex: 1,
  },
  directoryExplorerListContent: {
    gap: 8,
    paddingBottom: 4,
  },
  directoryExplorerEmptyState: {
    minHeight: 120,
    borderRadius: 12,
    borderWidth: theme.borders.thin,
    borderColor: theme.colors.borderSubtle,
    backgroundColor: theme.colors.surface,
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
  },
  directoryExplorerEntryButton: {
    minHeight: 62,
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 8,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  directoryExplorerEntryMain: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  directoryExplorerEntryTextWrap: {
    flex: 1,
    gap: 2,
  },
  directoryExplorerEntryName: {
    fontSize: theme.typography.body.fontSize,
    color: theme.colors.textPrimary,
    fontWeight: "600",
  },
  directoryExplorerFooter: {
    paddingHorizontal: 14,
    paddingTop: 10,
    paddingBottom: 14,
    gap: 8,
    borderTopWidth: theme.borders.thin,
    borderTopColor: theme.colors.borderInfo,
    backgroundColor: theme.colors.surface,
  },
  directoryExplorerNavRow: {
    flexDirection: "row",
    gap: 8,
  },
  directoryExplorerSecondaryButton: {
    flex: 1,
    minHeight: 42,
    borderRadius: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
  },
  directoryExplorerSecondaryButtonText: {
    fontSize: theme.typography.body.fontSize,
    color: theme.colors.infoAction,
    fontWeight: "700",
  },
  directoryExplorerPrimaryButton: {
    minHeight: 46,
    borderRadius: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  directoryExplorerPrimaryButtonText: {
    fontSize: theme.typography.input.fontSize,
    color: theme.colors.infoAction,
    fontWeight: "700",
  },
  modalCard: {
    borderRadius: 12,
    backgroundColor: theme.colors.surface,
    borderWidth: theme.borders.thin,
    borderColor: theme.colors.borderSoft,
    padding: 10,
    gap: 8,
  },
  modalCardLarge: {
    borderRadius: 12,
    backgroundColor: theme.colors.surface,
    borderWidth: theme.borders.thin,
    borderColor: theme.colors.borderSoft,
    padding: 10,
    gap: 8,
    maxHeight: "86%",
  },
  modalTitle: {
    fontSize: theme.typography.control.fontSize,
    fontWeight: "700",
    color: theme.colors.controlTextPrimary,
    marginBottom: 4,
  },
  modalOption: {
    borderWidth: theme.borders.thin,
    borderColor: theme.colors.borderSoft,
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 10,
  },
  modalOptionSelected: {
    borderColor: theme.colors.primaryAction,
    backgroundColor: theme.colors.surfaceActionSelected,
  },
  modalOptionText: {
    fontSize: theme.typography.body.fontSize,
    color: theme.colors.controlTextPrimary,
    fontWeight: "600",
  },
  modalOptionPrimaryRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  modalOptionPrimaryText: {
    flex: 1,
    fontSize: theme.typography.body.fontSize,
    color: theme.colors.controlTextPrimary,
    fontWeight: "600",
  },
  modalOptionContextPct: {
    fontSize: theme.typography.compact.fontSize,
    color: theme.colors.primaryAction,
    fontWeight: "700",
    textAlign: "right",
    minWidth: 44,
  },
  modalOptionTextSelected: {
    color: theme.colors.primaryAction,
  },
  modalOptionSubText: {
    marginTop: 2,
    fontSize: theme.typography.small.fontSize,
    color: theme.colors.textSubtle,
  },
  modalListScroll: {
    maxHeight: 360,
  },
  approvalBackdrop: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    padding: 24,
    backgroundColor: theme.approval.backdrop,
  },
  approvalModalCard: {
    width: "100%",
    maxWidth: 286,
    borderRadius: 14,
    backgroundColor: theme.approval.surface,
    overflow: "hidden",
    shadowColor: theme.approval.shadow,
    shadowOpacity: 0.2,
    shadowRadius: 22,
    shadowOffset: { width: 0, height: 10 },
    elevation: 18,
  },
  approvalAlertBody: {
    paddingTop: 18,
    paddingHorizontal: 18,
    paddingBottom: 15,
    alignItems: "center",
  },
  approvalModalTitle: {
    marginBottom: 6,
    fontSize: theme.typography.subtitle.fontSize,
    lineHeight: theme.typography.input.lineHeight,
    fontWeight: "600",
    color: theme.approval.text,
    textAlign: "center",
  },
  approvalSessionContextText: {
    alignSelf: "stretch",
    marginBottom: 7,
    fontSize: theme.typography.caption.fontSize,
    lineHeight: theme.typography.caption.lineHeight,
    color: theme.approval.textMuted,
    textAlign: "center",
  },
  approvalMessageText: {
    fontSize: theme.typography.compact.fontSize,
    lineHeight: theme.typography.compact.lineHeight,
    color: theme.approval.textSoft,
    textAlign: "center",
  },
  approvalCommandText: {
    alignSelf: "stretch",
    marginTop: 11,
    borderRadius: 8,
    backgroundColor: theme.approval.commandSurface,
    paddingHorizontal: 9,
    paddingVertical: 8,
    fontSize: theme.typography.small.fontSize,
    lineHeight: theme.typography.captionRelaxed.lineHeight,
    color: theme.approval.textSoft,
    textAlign: "left",
    fontFamily: Platform.select({ ios: "Menlo", android: "monospace", default: "monospace" }),
  },
  approvalActionList: {
    borderTopWidth: theme.borders.divider,
    borderTopColor: theme.approval.divider,
  },
  approvalAlertButton: {
    minHeight: 44,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderTopWidth: theme.borders.divider,
    borderTopColor: theme.approval.divider,
    backgroundColor: theme.approval.buttonSurface,
  },
  approvalAlertButtonPrimary: {
    borderTopWidth: 0,
  },
  approvalAlertButtonText: {
    fontSize: theme.typography.subtitle.fontSize,
    lineHeight: theme.typography.input.lineHeight,
    color: theme.approval.action,
    textAlign: "center",
  },
  approvalAlertButtonPrimaryText: {
    fontWeight: "600",
  },
  approvalAlertButtonDangerText: {
    color: theme.approval.danger,
  },
  } as const;
}

export const mediaModalStylesByTheme = createStylesByTheme(createMediaModalStyles);
