export const menuScreenStyles = {
  appDrawerPanel: {
    width: "86%",
    maxWidth: 360,
    backgroundColor: "#f8fafc",
  },
  appDrawerOverlay: {
    backgroundColor: "rgba(15, 23, 42, 0.28)",
  },
  appDrawerRoot: {
    flex: 1,
    backgroundColor: "#f8fafc",
  },
  appDrawerScroll: {
    flex: 1,
    backgroundColor: "#f8fafc",
  },
  appDrawerContent: {
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 18,
    gap: 14,
  },
  appDrawerTitle: {
    fontSize: 20,
    fontWeight: "700",
    color: "#0f172a",
    letterSpacing: 0.2,
  },
  appDrawerSearchSticky: {
    backgroundColor: "#f8fafc",
    paddingBottom: 2,
    zIndex: 10,
    elevation: 4,
  },
  appDrawerSearchBox: {
    minHeight: 42,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#cbd5e1",
    backgroundColor: "#ffffff",
    flexDirection: "row",
    alignItems: "center",
    paddingLeft: 12,
    paddingRight: 4,
  },
  appDrawerSearchInput: {
    flex: 1,
    minHeight: 40,
    paddingVertical: 8,
    paddingRight: 8,
    fontSize: 14,
    color: "#0f172a",
  },
  appDrawerSearchClearButton: {
    width: 34,
    height: 34,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
  },
  appDrawerSearchClearButtonText: {
    fontSize: 22,
    lineHeight: 24,
    color: "#64748b",
    fontWeight: "500",
  },
  appDrawerKeyboardAccessory: {
    minHeight: 44,
    paddingHorizontal: 12,
    paddingVertical: 6,
    backgroundColor: "transparent",
    alignItems: "flex-end",
    justifyContent: "center",
  },
  appDrawerKeyboardDismissButton: {
    minHeight: 32,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 6,
    backgroundColor: "transparent",
    alignItems: "center",
    justifyContent: "center",
  },
  appDrawerKeyboardDismissButtonText: {
    fontSize: 14,
    color: "#0f172a",
    fontWeight: "700",
  },
  appDrawerSection: {
    marginTop: 2,
    gap: 10,
  },
  appDrawerSectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  appDrawerSectionTitle: {
    fontSize: 13,
    fontWeight: "700",
    color: "#334155",
    letterSpacing: 0.5,
    textTransform: "uppercase",
  },
  appDrawerAddButton: {
    minHeight: 36,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 7,
    backgroundColor: "#eff6ff",
  },
  appDrawerAddButtonText: {
    fontSize: 13,
    fontWeight: "700",
    color: "#1e40af",
  },
  appDrawerDirectoryItem: {
    gap: 8,
    paddingHorizontal: 0,
    paddingVertical: 0,
  },
  appDrawerDirectoryItemSelected: {
    backgroundColor: "transparent",
  },
  appDrawerDirectoryHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  appDrawerExpandButton: {
    width: 44,
    height: 44,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "transparent",
  },
  appDrawerLoadingIndicatorWrap: {
    width: 20,
    height: 44,
    alignItems: "center",
    justifyContent: "center",
  },
  appDrawerUnreadCountBadge: {
    minWidth: 22,
    height: 22,
    paddingHorizontal: 6,
    borderRadius: 999,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#dbeafe",
  },
  appDrawerUnreadCountText: {
    fontSize: 11,
    fontWeight: "700",
    color: "#1d4ed8",
  },
  appDrawerDirectorySelectButton: {
    flex: 1,
    minHeight: 44,
    borderRadius: 8,
    paddingHorizontal: 4,
    paddingVertical: 8,
    backgroundColor: "transparent",
    gap: 4,
  },
  appDrawerDirectoryName: {
    fontSize: 16,
    color: "#0f172a",
    fontWeight: "500",
  },
  appDrawerDirectoryNameSelected: {
    color: "#1e3a8a",
    fontWeight: "700",
  },
  appDrawerDirectoryPath: {
    fontSize: 12,
    color: "#64748b",
  },
  appDrawerDirectoryPathSelected: {
    color: "#475569",
  },
  appDrawerSessionBlock: {
    gap: 8,
    marginLeft: 6,
    paddingLeft: 0,
  },
  appDrawerSessionItem: {
    position: "relative",
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 8,
    backgroundColor: "transparent",
  },
  appDrawerSessionItemSelected: {
    backgroundColor: "#f1f5f9",
  },
  appDrawerSessionPrimaryRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  appDrawerSessionMarkerDot: {
    width: 9,
    height: 9,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "rgba(15, 23, 42, 0.18)",
    flexShrink: 0,
  },
  appDrawerSessionPrimary: {
    flex: 1,
    fontSize: 14,
    color: "#0f172a",
    fontWeight: "500",
  },
  appDrawerSessionPrimarySelected: {
    color: "#0f766e",
  },
  appDrawerSessionContextPct: {
    fontSize: 13,
    color: "#0f766e",
    fontWeight: "700",
    textAlign: "right",
    minWidth: 40,
  },
  appDrawerSessionMetaText: {
    marginTop: 3,
    fontSize: 12,
    color: "#64748b",
  },
  appDrawerSessionUnreadDot: {
    position: "absolute",
    top: 8,
    right: 8,
    width: 8,
    height: 8,
    borderRadius: 999,
    backgroundColor: "#2563eb",
  },
  appDrawerSessionLoadMoreButton: {
    marginTop: 4,
    minHeight: 34,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#bfdbfe",
    backgroundColor: "#eff6ff",
    paddingHorizontal: 10,
    paddingVertical: 6,
    alignSelf: "flex-start",
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  appDrawerSessionLoadMoreButtonText: {
    fontSize: 12,
    fontWeight: "700",
    color: "#1e40af",
  },
  menuNavButton: {
    marginTop: 2,
    borderRadius: 12,
    backgroundColor: "#ffffff",
    paddingHorizontal: 14,
    paddingVertical: 12,
    gap: 4,
  },
  menuNavTitle: {
    fontSize: 13,
    fontWeight: "700",
    color: "#0f172a",
  },
  menuNavValue: {
    fontSize: 11,
    color: "#475569",
  },
} as const;
