import { VISUAL_THEMES, type VisualTheme } from "../theme/visualThemes";

export function createMenuScreenStyles(theme: VisualTheme) {
  return {
  appDrawerPanel: {
    width: "86%",
    maxWidth: 360,
    backgroundColor: theme.colors.surfaceRaised,
  },
  appDrawerOverlay: {
    backgroundColor: theme.colors.backdrop,
  },
  appDrawerRoot: {
    flex: 1,
    backgroundColor: theme.colors.surfaceRaised,
  },
  appDrawerScroll: {
    flex: 1,
    backgroundColor: theme.colors.surfaceRaised,
  },
  appDrawerContent: {
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 18,
    gap: 14,
  },
  appDrawerTitle: {
    fontSize: theme.typography.sectionTitle.fontSize,
    fontWeight: "700",
    color: theme.colors.textPrimary,
    letterSpacing: 0.2,
  },
  appDrawerSearchContainer: {
    marginHorizontal: 16,
    marginTop: 12,
    zIndex: 30,
    elevation: 12,
  },
  appDrawerSearchBox: {
    minHeight: 42,
    borderRadius: 8,
    borderWidth: theme.borders.thin,
    borderColor: theme.colors.border,
    backgroundColor: theme.colors.surface,
    flexDirection: "row",
    alignItems: "center",
    paddingLeft: 12,
    paddingRight: 4,
  },
  appDrawerSearchBoxFocused: {
    borderColor: theme.colors.primaryAction,
    borderWidth: theme.borders.strong,
    paddingLeft: 11,
    paddingRight: 3,
  },
  appDrawerSearchInput: {
    flex: 1,
    minHeight: 40,
    paddingVertical: 8,
    paddingRight: 8,
    fontSize: theme.typography.body.fontSize,
    color: theme.colors.textPrimary,
  },
  appDrawerSearchClearButton: {
    width: 34,
    height: 34,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
  },
  appDrawerSearchClearButtonText: {
    fontSize: theme.typography.headline.fontSize,
    lineHeight: theme.typography.title.lineHeight,
    color: theme.colors.textMuted,
    fontWeight: "500",
  },
  appDrawerSearchPopover: {
    position: "absolute",
    top: 48,
    left: 0,
    right: 0,
    borderRadius: 12,
    borderWidth: theme.borders.thin,
    borderColor: theme.colors.border,
    backgroundColor: theme.colors.surface,
    padding: 10,
    gap: 8,
    shadowColor: theme.colors.textPrimary,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.18,
    shadowRadius: 18,
    elevation: 12,
  },
  appDrawerSearchPopoverCompact: {
    maxHeight: 430,
  },
  appDrawerSearchTabs: {
    flexDirection: "row",
    borderRadius: 9,
    padding: 3,
    backgroundColor: theme.colors.surfaceMuted,
  },
  appDrawerSearchTab: {
    flex: 1,
    minHeight: 36,
    borderRadius: 7,
    alignItems: "center",
    justifyContent: "center",
  },
  appDrawerSearchTabSelected: {
    backgroundColor: theme.colors.surface,
    shadowColor: theme.colors.textPrimary,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.12,
    shadowRadius: 2,
    elevation: 2,
  },
  appDrawerSearchTabText: {
    color: theme.colors.textMuted,
    fontSize: theme.typography.compact.fontSize,
    fontWeight: "700",
  },
  appDrawerSearchTabTextSelected: {
    color: theme.colors.primaryAction,
  },
  appDrawerSearchDismissButton: {
    width: 36,
    minHeight: 36,
    borderRadius: 7,
    alignItems: "center",
    justifyContent: "center",
  },
  appDrawerSearchDismissButtonText: {
    color: theme.colors.textMuted,
    fontSize: theme.typography.sectionTitle.fontSize,
    lineHeight: theme.typography.subtitleDense.lineHeight,
  },
  appDrawerSearchDirectoryStatus: {
    minHeight: 42,
    justifyContent: "center",
    paddingHorizontal: 6,
  },
  appDrawerSearchStatusText: {
    color: theme.colors.textMuted,
    fontSize: theme.typography.compact.fontSize,
    lineHeight: theme.typography.compactRelaxed.lineHeight,
  },
  appDrawerSearchOptionsSummary: {
    minHeight: 42,
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 6,
    backgroundColor: theme.colors.surfaceRaised,
    justifyContent: "center",
    gap: 2,
  },
  appDrawerSearchOptionsSummaryText: {
    color: theme.colors.textSecondary,
    fontSize: theme.typography.small.fontSize,
    fontWeight: "700",
  },
  appDrawerSearchOptionsValue: {
    color: theme.colors.textMuted,
    fontSize: theme.typography.caption.fontSize,
  },
  appDrawerSearchOptions: {
    gap: 6,
    paddingHorizontal: 4,
  },
  appDrawerSearchOptionLabel: {
    color: theme.colors.textMuted,
    fontSize: theme.typography.caption.fontSize,
    fontWeight: "700",
  },
  appDrawerSearchOptionRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
  },
  appDrawerSearchChip: {
    minHeight: 32,
    borderRadius: 16,
    borderWidth: theme.borders.thin,
    borderColor: theme.colors.border,
    paddingHorizontal: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  appDrawerSearchChipSelected: {
    borderColor: theme.colors.primaryAction,
    backgroundColor: theme.colors.primaryActionMuted,
  },
  appDrawerSearchChipText: {
    color: theme.colors.textSecondary,
    fontSize: theme.typography.small.fontSize,
    fontWeight: "600",
  },
  appDrawerSearchScopeText: {
    color: theme.colors.textMuted,
    fontSize: theme.typography.caption.fontSize,
    paddingHorizontal: 4,
  },
  appDrawerSearchResults: {
    flex: 1,
    minHeight: 0,
  },
  appDrawerSearchResultsContent: {
    gap: 8,
  },
  appDrawerSearchLoading: {
    minHeight: 56,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  appDrawerSearchError: {
    color: theme.tones.danger.foreground,
    fontSize: theme.typography.compact.fontSize,
    lineHeight: theme.typography.compactRelaxed.lineHeight,
    paddingVertical: 10,
  },
  appDrawerSearchResult: {
    borderWidth: theme.borders.thin,
    borderColor: theme.colors.borderSubtle,
    borderRadius: 10,
    backgroundColor: theme.colors.surface,
    paddingHorizontal: 10,
    paddingVertical: 9,
    gap: 6,
  },
  appDrawerSearchResultPressed: {
    backgroundColor: theme.colors.surfaceActionSoft,
    borderColor: theme.colors.primaryActionBorder,
  },
  appDrawerSearchResultTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  appDrawerSearchResultTitle: {
    flex: 1,
    minWidth: 0,
    color: theme.colors.textPrimary,
    fontSize: theme.typography.compact.fontSize,
    fontWeight: "700",
  },
  appDrawerSearchResultDate: {
    color: theme.colors.borderStrong,
    fontSize: theme.typography.micro.fontSize,
  },
  appDrawerSearchResultMetaRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  appDrawerSearchResultDirectory: {
    flex: 1,
    color: theme.colors.primaryAction,
    fontSize: theme.typography.caption.fontSize,
    fontWeight: "600",
  },
  appDrawerSearchResultMeta: {
    color: theme.colors.textMuted,
    fontSize: theme.typography.micro.fontSize,
    textAlign: "right",
  },
  appDrawerSearchResultSnippet: {
    color: theme.colors.textPrimary,
    fontSize: theme.typography.compact.fontSize,
    lineHeight: theme.typography.compactRelaxed.lineHeight,
  },
  appDrawerSearchWarning: {
    color: theme.colors.warningText,
    fontSize: theme.typography.caption.fontSize,
    paddingVertical: 6,
  },
  appDrawerSearchMoreButton: {
    minHeight: 40,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
  },
  appDrawerSearchMoreButtonText: {
    color: theme.colors.infoAction,
    fontSize: theme.typography.compact.fontSize,
    fontWeight: "700",
  },
  appDrawerSearchProgressText: {
    color: theme.colors.textMuted,
    fontSize: theme.typography.small.fontSize,
    textAlign: "center",
  },
  appDrawerKeyboardAccessory: {
    minHeight: 44,
    paddingHorizontal: 12,
    paddingVertical: 6,
    backgroundColor: "transparent",
    alignItems: "flex-end",
    justifyContent: "center",
  },
  appDrawerKeyboardDismissButton: {
    minHeight: 32,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 6,
    backgroundColor: "transparent",
    alignItems: "center",
    justifyContent: "center",
  },
  appDrawerKeyboardDismissButtonText: {
    fontSize: theme.typography.body.fontSize,
    color: theme.colors.textPrimary,
    fontWeight: "700",
  },
  appDrawerSection: {
    marginTop: 2,
    gap: 10,
  },
  appDrawerSectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  appDrawerSectionTitle: {
    fontSize: theme.typography.compact.fontSize,
    fontWeight: "700",
    color: theme.colors.textSecondary,
    letterSpacing: 0.5,
    textTransform: "uppercase",
  },
  appDrawerAddButton: {
    minHeight: 36,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 7,
    backgroundColor: theme.colors.surfaceSelected,
  },
  appDrawerAddButtonText: {
    fontSize: theme.typography.compact.fontSize,
    fontWeight: "700",
    color: theme.colors.infoAction,
  },
  appDrawerDirectoryItem: {
    gap: 8,
    paddingHorizontal: 0,
    paddingVertical: 0,
  },
  appDrawerDirectoryItemSelected: {
    backgroundColor: "transparent",
  },
  appDrawerDirectoryHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  appDrawerExpandButton: {
    width: 44,
    height: 44,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "transparent",
  },
  appDrawerSessionSync: {
    gap: 5,
    marginBottom: 8,
  },
  appDrawerSessionSyncTrack: {
    height: 5,
    borderRadius: 3,
    overflow: "hidden",
    backgroundColor: theme.colors.primaryActionMuted,
  },
  appDrawerSessionSyncFill: {
    height: "100%",
    backgroundColor: theme.colors.primaryAction,
  },
  appDrawerSessionSyncText: {
    color: theme.colors.textMuted,
    fontSize: theme.typography.caption.fontSize,
  },
  appDrawerSessionSyncError: {
    marginBottom: 8,
    color: theme.colors.warningText,
    fontSize: theme.typography.caption.fontSize,
    fontWeight: "700",
  },
  appDrawerSessionSyncFatalError: {
    color: theme.tones.danger.foreground,
  },
  appDrawerDirectoryReadProgress: {
    gap: 4,
    paddingHorizontal: 4,
  },
  appDrawerDirectoryReadProgressTrack: {
    height: 4,
    borderRadius: 2,
    overflow: "hidden",
    backgroundColor: theme.colors.infoMuted,
  },
  appDrawerDirectoryReadProgressFill: {
    height: "100%",
    backgroundColor: theme.colors.accent,
  },
  appDrawerDirectoryReadProgressText: {
    color: theme.colors.textMuted,
    fontSize: theme.typography.caption.fontSize,
  },
  appDrawerUnreadCountBadge: {
    minWidth: 22,
    height: 22,
    paddingHorizontal: 6,
    borderRadius: 999,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: theme.colors.infoMuted,
  },
  appDrawerUnreadCountText: {
    fontSize: theme.typography.caption.fontSize,
    fontWeight: "700",
    color: theme.colors.accentStrong,
  },
  appDrawerDirectorySelectButton: {
    flex: 1,
    minHeight: 44,
    borderRadius: 8,
    paddingHorizontal: 4,
    paddingVertical: 8,
    backgroundColor: "transparent",
    gap: 4,
  },
  appDrawerDirectoryName: {
    fontSize: theme.typography.control.fontSize,
    color: theme.colors.textPrimary,
    fontWeight: "500",
  },
  appDrawerDirectoryNameSelected: {
    color: theme.colors.accentStrong,
    fontWeight: "700",
  },
  appDrawerDirectoryPath: {
    fontSize: theme.typography.small.fontSize,
    color: theme.colors.textMuted,
  },
  appDrawerDirectoryPathSelected: {
    color: theme.colors.textMuted,
  },
  appDrawerSessionBlock: {
    gap: 8,
    marginLeft: 6,
    paddingLeft: 0,
  },
  appDrawerSessionItem: {
    position: "relative",
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 8,
    backgroundColor: "transparent",
  },
  appDrawerSessionItemSelected: {
    backgroundColor: theme.colors.surfaceMuted,
  },
  appDrawerSessionTreeNode: {
    gap: 4,
  },
  appDrawerSessionChildrenBlock: {
    gap: 6,
    marginTop: 4,
    paddingLeft: 8,
    borderLeftWidth: theme.borders.thin,
    borderLeftColor: theme.colors.borderSubtle,
  },
  appDrawerSessionPrimaryRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  appDrawerSessionChildToggle: {
    width: 24,
    height: 24,
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  appDrawerSessionMarkerDot: {
    width: 9,
    height: 9,
    borderRadius: 999,
    borderWidth: theme.borders.thin,
    borderColor: theme.colors.borderTranslucent,
    flexShrink: 0,
  },
  appDrawerSessionPrimary: {
    flex: 1,
    fontSize: theme.typography.body.fontSize,
    color: theme.colors.textPrimary,
    fontWeight: "500",
  },
  appDrawerSessionPrimarySelected: {
    color: theme.colors.primaryAction,
  },
  appDrawerSessionContextPct: {
    fontSize: theme.typography.compact.fontSize,
    color: theme.colors.primaryAction,
    fontWeight: "700",
    textAlign: "right",
    minWidth: 40,
  },
  appDrawerSessionMetaText: {
    marginTop: 3,
    fontSize: theme.typography.small.fontSize,
    color: theme.colors.textMuted,
  },
  appDrawerSessionUnreadDot: {
    position: "absolute",
    top: 8,
    right: 8,
    width: 8,
    height: 8,
    borderRadius: 999,
    backgroundColor: theme.colors.accent,
  },
  appDrawerSessionLoadMoreButton: {
    marginTop: 4,
    minHeight: 34,
    borderRadius: 8,
    borderWidth: theme.borders.thin,
    borderColor: theme.colors.infoBorder,
    backgroundColor: theme.colors.surfaceSelected,
    paddingHorizontal: 10,
    paddingVertical: 6,
    alignSelf: "flex-start",
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  appDrawerSessionLoadMoreButtonText: {
    fontSize: theme.typography.small.fontSize,
    fontWeight: "700",
    color: theme.colors.infoAction,
  },
  menuNavButton: {
    marginTop: 2,
    borderRadius: 12,
    backgroundColor: theme.colors.surface,
    paddingHorizontal: 14,
    paddingVertical: 12,
    gap: 4,
  },
  menuNavTitle: {
    fontSize: theme.typography.compact.fontSize,
    fontWeight: "700",
    color: theme.colors.textPrimary,
  },
  menuNavValue: {
    fontSize: theme.typography.caption.fontSize,
    color: theme.colors.textMuted,
  },
  } as const;
}

export const menuScreenStylesByTheme = {
  standard: createMenuScreenStyles(VISUAL_THEMES.standard),
  highLegibility: createMenuScreenStyles(VISUAL_THEMES.highLegibility),
};
