export const recordingDebugStyles = {
  recordingSectionCard: {
    marginTop: 6,
    borderWidth: 1,
    borderColor: "#d1d5db",
    borderRadius: 10,
    backgroundColor: "#ffffff",
    paddingHorizontal: 10,
    paddingVertical: 9,
    gap: 8,
  },
  recordingSectionTitle: {
    fontSize: 12,
    fontWeight: "700",
    color: "#334155",
  },
  recordingRadioRow: {
    borderWidth: 1,
    borderColor: "#d1d5db",
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 8,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: "#f8fafc",
  },
  recordingRadioRowSelected: {
    borderColor: "#0f766e",
    backgroundColor: "#f0fdfa",
  },
  recordingRadioTextWrap: {
    flex: 1,
    gap: 2,
  },
  recordingRadioTitle: {
    fontSize: 13,
    fontWeight: "700",
    color: "#111827",
  },
  recordingRadioTitleSelected: {
    color: "#0f766e",
  },
  recordingRadioHint: {
    fontSize: 11,
    color: "#64748b",
  },
  recordingDetailGrid: {
    flexDirection: "row",
    gap: 8,
  },
  recordingDetailField: {
    flex: 1,
    gap: 4,
  },
  recordingDetailLabel: {
    fontSize: 11,
    fontWeight: "700",
    color: "#475569",
  },
  recordingDetailInput: {
    marginTop: 0,
    paddingVertical: 8,
  },
  autoWaveformCard: {
    marginTop: 6,
    borderWidth: 1,
    borderColor: "#d1d5db",
    borderRadius: 10,
    backgroundColor: "#ffffff",
    paddingHorizontal: 8,
    paddingVertical: 6,
  },
  autoWaveformGif: {
    borderRadius: 8,
    opacity: 0.84,
  },
  autoWaveformGifActive: {
    opacity: 1,
  },
  directSttDebugCard: {
    flex: 1,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#dbe4ef",
    backgroundColor: "#f8fafc",
    paddingHorizontal: 10,
    paddingVertical: 8,
    gap: 4,
  },
  directSttDebugTitle: {
    fontSize: 12,
    fontWeight: "700",
    color: "#334155",
  },
  directSttDebugBody: {
    fontSize: 13,
    lineHeight: 18,
    color: "#0f172a",
  },
  autoWaveformDebugOverlay: {
    position: "absolute",
    top: 4,
    right: 6,
    left: 6,
    zIndex: 2,
    backgroundColor: "rgba(15, 23, 42, 0.72)",
    borderRadius: 6,
    paddingHorizontal: 6,
    paddingVertical: 2,
  },
  autoWaveformDebugOverlayText: {
    color: "#e2e8f0",
    fontSize: 9,
    fontWeight: "700",
    letterSpacing: 0.2,
  },
  autoWaveSpinnerOverlay: {
    position: "absolute",
    left: 8,
    bottom: 6,
    width: 14,
    height: 14,
    zIndex: 4,
    alignItems: "center",
    justifyContent: "center",
  },
  autoWaveSpinner: {
    width: 12,
    height: 12,
    borderRadius: 999,
    borderWidth: 2,
    borderColor: "rgba(15,23,42,0.28)",
    borderTopColor: "#f97316",
    backgroundColor: "transparent",
  },
} as const;
