import { createStylesByTheme, type VisualTheme } from "../theme/visualThemes";

export function createSettingsScreenStyles(theme: VisualTheme) {
  return {
  settingsScreen: {
    flex: 1,
    backgroundColor: theme.colors.surfaceRaised,
  },
  settingsContent: {
    width: "100%",
    maxWidth: 760,
    alignSelf: "center",
    paddingHorizontal: 18,
    paddingTop: 12,
    paddingBottom: 52,
    gap: 22,
  },
  settingsBackButton: {
    alignSelf: "flex-start",
    minHeight: 40,
    justifyContent: "center",
    paddingHorizontal: 2,
  },
  settingsBackButtonText: {
    color: theme.colors.controlAccent,
    fontSize: theme.typography.control.fontSize,
    fontWeight: "600",
  },
  settingsTitle: {
    color: theme.colors.groupedTextPrimary,
    ...theme.typography.hero,
    fontWeight: "800",
  },
  settingsSection: {
    gap: 10,
  },
  settingsSectionHeader: {
    paddingHorizontal: 10,
  },
  settingsSectionTitle: {
    color: theme.colors.groupedTextMuted,
    ...theme.typography.subtitleDense,
    fontWeight: "700",
  },
  settingsGroup: {
    overflow: "hidden",
    borderRadius: 22,
    backgroundColor: theme.colors.surface,
    paddingHorizontal: 16,
  },
  settingsRow: {
    minHeight: 58,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingVertical: 11,
  },
  settingsRowDivider: {
    borderBottomWidth: theme.borders.thin,
    borderBottomColor: theme.colors.groupedDivider,
  },
  settingsRowLabelWrap: {
    flex: 1,
    minWidth: 0,
  },
  settingsRowLabel: {
    color: theme.colors.groupedTextPrimary,
    ...theme.typography.inputDense,
    fontWeight: "600",
  },
  settingsRowDescription: {
    marginTop: 2,
    color: theme.colors.groupedTextMuted,
    ...theme.typography.captionDense,
  },
  settingsRowValue: {
    maxWidth: "42%",
    color: theme.colors.groupedTextMuted,
    ...theme.typography.inputDense,
    textAlign: "right",
  },
  settingsInputRow: {
    minHeight: 76,
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
    paddingVertical: 12,
  },
  settingsInputContent: {
    flex: 1,
    minWidth: 0,
    gap: 5,
  },
  settingsInlineInput: {
    minHeight: 34,
    borderRadius: 9,
    backgroundColor: theme.colors.surfaceGrouped,
    paddingHorizontal: 10,
    paddingVertical: 7,
    color: theme.colors.groupedTextPrimary,
    fontSize: theme.typography.body.fontSize,
  },
  settingsPrimaryButton: {
    minHeight: 40,
    alignSelf: "flex-start",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 7,
    borderRadius: 9,
    backgroundColor: theme.colors.controlAccent,
    paddingHorizontal: 14,
  },
  settingsPrimaryButtonText: {
    color: theme.colors.textOnAccent,
    fontSize: theme.typography.label.fontSize,
    fontWeight: "700",
  },
  settingsButtonRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  settingsSuccessText: {
    color: theme.colors.successText,
    ...theme.typography.small,
  },
  settingsErrorText: {
    color: theme.tones.danger.foreground,
    ...theme.typography.small,
  },
  settingsStepper: {
    flexDirection: "row",
    alignItems: "center",
    overflow: "hidden",
    borderWidth: theme.borders.thin,
    borderColor: theme.colors.groupedBorder,
    borderRadius: 9,
  },
  settingsStepperButton: {
    width: 36,
    minHeight: 34,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: theme.colors.groupedControlSurface,
  },
  settingsStepperInput: {
    width: 48,
    minHeight: 34,
    borderLeftWidth: theme.borders.thin,
    borderRightWidth: theme.borders.thin,
    borderColor: theme.colors.groupedBorder,
    paddingHorizontal: 5,
    paddingVertical: 6,
    color: theme.colors.groupedTextPrimary,
    fontSize: theme.typography.body.fontSize,
    textAlign: "center",
  },
  settingsActionText: {
    color: theme.colors.controlAccent,
    ...theme.typography.inputDense,
    fontWeight: "600",
  },
  settingsDangerText: {
    color: theme.colors.controlDanger,
    ...theme.typography.inputDense,
    fontWeight: "600",
  },
  settingsFooterText: {
    paddingHorizontal: 10,
    color: theme.colors.groupedTextMuted,
    ...theme.typography.captionRelaxed,
  },
  settingsSelectBackdrop: {
    flex: 1,
    justifyContent: "center",
    backgroundColor: theme.colors.controlBackdrop,
    padding: 20,
  },
  settingsSelectCard: {
    width: "100%",
    maxWidth: 520,
    maxHeight: "72%",
    alignSelf: "center",
    overflow: "hidden",
    borderRadius: 20,
    backgroundColor: theme.colors.surface,
    paddingHorizontal: 16,
    paddingBottom: 10,
  },
  settingsSelectHeader: {
    minHeight: 58,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderBottomWidth: theme.borders.thin,
    borderBottomColor: theme.colors.groupedDivider,
  },
  settingsSelectTitle: {
    color: theme.colors.groupedTextPrimary,
    fontSize: theme.typography.title.fontSize,
    fontWeight: "700",
  },
  settingsSelectCloseButton: {
    width: 40,
    height: 40,
    alignItems: "center",
    justifyContent: "center",
  },
  settingsSelectSearchInput: {
    minHeight: 40,
    marginVertical: 10,
    borderRadius: 10,
    backgroundColor: theme.colors.surfaceGrouped,
    paddingHorizontal: 12,
    color: theme.colors.groupedTextPrimary,
    fontSize: theme.typography.body.fontSize,
  },
  settingsSelectOption: {
    minHeight: 50,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    borderBottomWidth: theme.borders.thin,
    borderBottomColor: theme.colors.groupedDivider,
    paddingVertical: 10,
  },
  settingsSelectOptionTextWrap: {
    flex: 1,
    minWidth: 0,
  },
  settingsSelectOptionLabel: {
    color: theme.colors.groupedTextPrimary,
    ...theme.typography.inputDense,
  },
  settingsSelectOptionLabelSelected: {
    color: theme.colors.controlAccent,
    fontWeight: "700",
  },
  settingsSelectOptionDescription: {
    marginTop: 2,
    color: theme.colors.groupedTextMuted,
    ...theme.typography.captionDense,
  },
  settingsSelectEmpty: {
    paddingVertical: 24,
    color: theme.colors.groupedTextMuted,
    fontSize: theme.typography.body.fontSize,
    textAlign: "center",
  },
  } as const;
}

export const settingsScreenStylesByTheme = createStylesByTheme(createSettingsScreenStyles);
