export const settingsScreenStyles = {
  settingsScreen: {
    flex: 1,
    backgroundColor: "#f2f2f7",
  },
  settingsContent: {
    width: "100%",
    maxWidth: 760,
    alignSelf: "center",
    paddingHorizontal: 18,
    paddingTop: 12,
    paddingBottom: 52,
    gap: 22,
  },
  settingsBackButton: {
    alignSelf: "flex-start",
    minHeight: 40,
    justifyContent: "center",
    paddingHorizontal: 2,
  },
  settingsBackButtonText: {
    color: "#0a84ff",
    fontSize: 16,
    fontWeight: "600",
  },
  settingsTitle: {
    color: "#111111",
    fontSize: 32,
    lineHeight: 38,
    fontWeight: "800",
  },
  settingsSection: {
    gap: 10,
  },
  settingsSectionHeader: {
    paddingHorizontal: 10,
  },
  settingsSectionTitle: {
    color: "#8e8e93",
    fontSize: 17,
    lineHeight: 22,
    fontWeight: "700",
  },
  settingsGroup: {
    overflow: "hidden",
    borderRadius: 22,
    backgroundColor: "#ffffff",
    paddingHorizontal: 16,
  },
  settingsRow: {
    minHeight: 58,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingVertical: 11,
  },
  settingsRowDivider: {
    borderBottomWidth: 1,
    borderBottomColor: "#e5e5ea",
  },
  settingsRowLabelWrap: {
    flex: 1,
    minWidth: 0,
  },
  settingsRowLabel: {
    color: "#111111",
    fontSize: 15,
    lineHeight: 20,
    fontWeight: "600",
  },
  settingsRowDescription: {
    marginTop: 2,
    color: "#8e8e93",
    fontSize: 11,
    lineHeight: 15,
  },
  settingsRowValue: {
    maxWidth: "42%",
    color: "#8e8e93",
    fontSize: 15,
    lineHeight: 20,
    textAlign: "right",
  },
  settingsInputRow: {
    minHeight: 76,
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
    paddingVertical: 12,
  },
  settingsInputContent: {
    flex: 1,
    minWidth: 0,
    gap: 5,
  },
  settingsInlineInput: {
    minHeight: 34,
    borderRadius: 9,
    backgroundColor: "#f2f2f7",
    paddingHorizontal: 10,
    paddingVertical: 7,
    color: "#111111",
    fontSize: 14,
  },
  settingsStepper: {
    flexDirection: "row",
    alignItems: "center",
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "#d1d1d6",
    borderRadius: 9,
  },
  settingsStepperButton: {
    width: 36,
    minHeight: 34,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#f7f7f9",
  },
  settingsStepperInput: {
    width: 48,
    minHeight: 34,
    borderLeftWidth: 1,
    borderRightWidth: 1,
    borderColor: "#d1d1d6",
    paddingHorizontal: 5,
    paddingVertical: 6,
    color: "#111111",
    fontSize: 14,
    textAlign: "center",
  },
  settingsActionText: {
    color: "#0a84ff",
    fontSize: 15,
    lineHeight: 20,
    fontWeight: "600",
  },
  settingsDangerText: {
    color: "#ff3b30",
    fontSize: 15,
    lineHeight: 20,
    fontWeight: "600",
  },
  settingsFooterText: {
    paddingHorizontal: 10,
    color: "#8e8e93",
    fontSize: 11,
    lineHeight: 16,
  },
  settingsSelectBackdrop: {
    flex: 1,
    justifyContent: "center",
    backgroundColor: "rgba(0, 0, 0, 0.32)",
    padding: 20,
  },
  settingsSelectCard: {
    width: "100%",
    maxWidth: 520,
    maxHeight: "72%",
    alignSelf: "center",
    overflow: "hidden",
    borderRadius: 20,
    backgroundColor: "#ffffff",
    paddingHorizontal: 16,
    paddingBottom: 10,
  },
  settingsSelectHeader: {
    minHeight: 58,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderBottomWidth: 1,
    borderBottomColor: "#e5e5ea",
  },
  settingsSelectTitle: {
    color: "#111111",
    fontSize: 18,
    fontWeight: "700",
  },
  settingsSelectCloseButton: {
    width: 40,
    height: 40,
    alignItems: "center",
    justifyContent: "center",
  },
  settingsSelectSearchInput: {
    minHeight: 40,
    marginVertical: 10,
    borderRadius: 10,
    backgroundColor: "#f2f2f7",
    paddingHorizontal: 12,
    color: "#111111",
    fontSize: 14,
  },
  settingsSelectOption: {
    minHeight: 50,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    borderBottomWidth: 1,
    borderBottomColor: "#e5e5ea",
    paddingVertical: 10,
  },
  settingsSelectOptionTextWrap: {
    flex: 1,
    minWidth: 0,
  },
  settingsSelectOptionLabel: {
    color: "#111111",
    fontSize: 15,
    lineHeight: 20,
  },
  settingsSelectOptionLabelSelected: {
    color: "#0a84ff",
    fontWeight: "700",
  },
  settingsSelectOptionDescription: {
    marginTop: 2,
    color: "#8e8e93",
    fontSize: 11,
    lineHeight: 15,
  },
  settingsSelectEmpty: {
    paddingVertical: 24,
    color: "#8e8e93",
    fontSize: 14,
    textAlign: "center",
  },
} as const;
