import { useMemo } from "react";
import type { AppSettingsContextValue } from "../contexts/AppSettingsContext";
import type { AppShellContextValue } from "../contexts/AppShellContext";
import type { AudioLabContextValue } from "../contexts/AudioLabContext";
import type { ChatComposerContextValue } from "../contexts/ChatComposerContext";
import type { ChatDiagnosticsContextValue } from "../contexts/ChatDiagnosticsContext";
import type { ChatScreenContextValue } from "../contexts/ChatScreenContext";
import type { ChatVisualContextValue } from "../contexts/ChatVisualContext";
import type { ConversationContextValue } from "../contexts/ConversationContext";
import type { DebugConversationContextValue } from "../contexts/DebugConversationContext";
import type { DebugRuntimeContextValue } from "../contexts/DebugRuntimeContext";
import type { DebugSpeechContextValue } from "../contexts/DebugSpeechContext";
import type { YouTubePlayerContextValue } from "../contexts/YouTubePlayerContext";
import type {
  CodexAuthProfilesSnapshot,
  CodexCliStatusSnapshot,
  GitChangedFilesDirectoryState,
} from "../types/appTypes";

export function useAppShellContextValue(args: AppShellContextValue): AppShellContextValue {
  const {
    activeScreen,
    drawerOpen,
    setActiveScreen,
    setDrawerOpen,
    openDrawer,
    closeDrawer,
    openDebugScreen,
    openAudioLabScreen,
    openMiniBoardScreen,
    openCloudflareTunnelMonitorScreen,
  } = args;

  return useMemo(
    () => ({
      activeScreen,
      drawerOpen,
      setActiveScreen,
      setDrawerOpen,
      openDrawer,
      closeDrawer,
      openDebugScreen,
      openAudioLabScreen,
      openMiniBoardScreen,
      openCloudflareTunnelMonitorScreen,
    }),
    [activeScreen, drawerOpen, setActiveScreen, setDrawerOpen, openDrawer, closeDrawer, openDebugScreen, openAudioLabScreen, openMiniBoardScreen, openCloudflareTunnelMonitorScreen]
  );
}

export function useAppSettingsContextValue(args: AppSettingsContextValue): AppSettingsContextValue {
  const {
    runnerUrl,
    llmDirectory,
    codexWsUrl,
    codexWsToken,
    runnerToken,
    cloudflareAccessClientId,
    cloudflareAccessEnabled,
    cloudflareRunnerUrl,
    cloudflareRunnerWsUrl,
    localRunnerUrl,
    localRunnerWsUrl,
    executionEnvironment,
    isExpoGo,
    isDev,
    defaultCodexWsUrl,
    codexApprovalPolicy,
    selectedModelLabel,
    modelRef,
    reasoningEffort,
    modelOptions,
    thinkOptions,
    ttsProvider,
    sttProvider,
    voicesLoading,
    filteredVoices,
    ttsSpeedInput,
    ttsSpeed,
    voiceFilter,
    selectedVoiceId,
    recordingQualityPreset,
    recordingTuning,
    autoTranscribeOnStop,
    autoReplyAfterStt,
    autoBargeInEnabled,
    autoSpeakerPriorityEnabled,
    autoSpeakAfterReply,
    changeRunnerUrl,
    changeLlmDirectory,
    changeCodexWsUrl,
    changeCodexWsToken,
    changeRunnerToken,
    clearCloudflareAccessCredentials,
    applyCloudflareRunnerPairing,
    selectCodexApprovalPolicy,
    loadVoices,
    changeTtsSpeedInput,
    commitTtsSpeedInput,
    decreaseTtsSpeed,
    increaseTtsSpeed,
    changeVoiceFilter,
    selectVoiceId,
    selectTtsProvider,
    selectSttProvider,
    applyRecordingQualityPreset,
    changeRecordingSampleRate,
    changeRecordingBitRate,
    changeRecordingChannels,
    changeRecordingProgressUpdateInterval,
    toggleAutoTranscribeOnStop,
    toggleAutoReplyAfterStt,
    toggleAutoBargeInEnabled,
    toggleAutoSpeakerPriorityEnabled,
    toggleAutoSpeakAfterReply,
    openModelSelect,
    openThinkSelect,
    modelSelectOpen,
    thinkSelectOpen,
    setModelSelectOpen,
    setThinkSelectOpen,
    selectModel,
    selectThinkOption,
  } = args;

  return useMemo(
    () => ({
      runnerUrl,
      llmDirectory,
      codexWsUrl,
      codexWsToken,
      runnerToken,
      cloudflareAccessClientId,
      cloudflareAccessEnabled,
      cloudflareRunnerUrl,
      cloudflareRunnerWsUrl,
      localRunnerUrl,
      localRunnerWsUrl,
      executionEnvironment,
      isExpoGo,
      isDev,
      defaultCodexWsUrl,
      codexApprovalPolicy,
      selectedModelLabel,
      modelRef,
      reasoningEffort,
      modelOptions,
      thinkOptions,
      ttsProvider,
      sttProvider,
      voicesLoading,
      filteredVoices,
      ttsSpeedInput,
      ttsSpeed,
      voiceFilter,
      selectedVoiceId,
      recordingQualityPreset,
      recordingTuning,
      autoTranscribeOnStop,
      autoReplyAfterStt,
      autoBargeInEnabled,
      autoSpeakerPriorityEnabled,
      autoSpeakAfterReply,
      changeRunnerUrl,
      changeLlmDirectory,
      changeCodexWsUrl,
      changeCodexWsToken,
      changeRunnerToken,
      clearCloudflareAccessCredentials,
      applyCloudflareRunnerPairing,
      selectCodexApprovalPolicy,
      loadVoices,
      changeTtsSpeedInput,
      commitTtsSpeedInput,
      decreaseTtsSpeed,
      increaseTtsSpeed,
      changeVoiceFilter,
      selectVoiceId,
      selectTtsProvider,
      selectSttProvider,
      applyRecordingQualityPreset,
      changeRecordingSampleRate,
      changeRecordingBitRate,
      changeRecordingChannels,
      changeRecordingProgressUpdateInterval,
      toggleAutoTranscribeOnStop,
      toggleAutoReplyAfterStt,
      toggleAutoBargeInEnabled,
      toggleAutoSpeakerPriorityEnabled,
      toggleAutoSpeakAfterReply,
      openModelSelect,
      openThinkSelect,
      modelSelectOpen,
      thinkSelectOpen,
      setModelSelectOpen,
      setThinkSelectOpen,
      selectModel,
      selectThinkOption,
    }),
    [
      runnerUrl,
      llmDirectory,
      codexWsUrl,
      codexWsToken,
      runnerToken,
      cloudflareAccessClientId,
      cloudflareAccessEnabled,
      cloudflareRunnerUrl,
      cloudflareRunnerWsUrl,
      localRunnerUrl,
      localRunnerWsUrl,
      executionEnvironment,
      isExpoGo,
      isDev,
      defaultCodexWsUrl,
      codexApprovalPolicy,
      selectedModelLabel,
      modelRef,
      reasoningEffort,
      modelOptions,
      thinkOptions,
      ttsProvider,
      sttProvider,
      voicesLoading,
      filteredVoices,
      ttsSpeedInput,
      ttsSpeed,
      voiceFilter,
      selectedVoiceId,
      recordingQualityPreset,
      recordingTuning,
      autoTranscribeOnStop,
      autoReplyAfterStt,
      autoBargeInEnabled,
      autoSpeakerPriorityEnabled,
      autoSpeakAfterReply,
      changeRunnerUrl,
      changeLlmDirectory,
      changeCodexWsUrl,
      changeCodexWsToken,
      changeRunnerToken,
      clearCloudflareAccessCredentials,
      applyCloudflareRunnerPairing,
      selectCodexApprovalPolicy,
      loadVoices,
      changeTtsSpeedInput,
      commitTtsSpeedInput,
      decreaseTtsSpeed,
      increaseTtsSpeed,
      changeVoiceFilter,
      selectVoiceId,
      selectTtsProvider,
      selectSttProvider,
      applyRecordingQualityPreset,
      changeRecordingSampleRate,
      changeRecordingBitRate,
      changeRecordingChannels,
      changeRecordingProgressUpdateInterval,
      toggleAutoTranscribeOnStop,
      toggleAutoReplyAfterStt,
      toggleAutoBargeInEnabled,
      toggleAutoSpeakerPriorityEnabled,
      toggleAutoSpeakAfterReply,
      openModelSelect,
      openThinkSelect,
      modelSelectOpen,
      thinkSelectOpen,
      setModelSelectOpen,
      setThinkSelectOpen,
      selectModel,
      selectThinkOption,
    ]
  );
}

export function useConversationContextValue(
  args: ConversationContextValue
): ConversationContextValue {
  const {
    conversationMessages,
    llmSessionRestoreLoading,
    selectedSessionExecutionFact,
    selectedThreadStatusType,
    selectedSessionWaitingApproval,
    waitingApprovalResumeLoading,
    waitingApprovalResumeStatusText,
    directorySelectOpen,
    selectedDirectoryLabel,
    directoryExplorerPathLabel,
    directoryExplorerHasParent,
    directoryExplorerLoading,
    directoryExplorerError,
    directoryExplorerEntries,
    llmSessionRestoreError,
    registeredDirectories,
    directorySessionsById,
    sessionTitleOverridesById,
    sessionMarkerColorsById,
    selectedLlmSessionId,
    hasSelectedDirectory,
    selectedDirectoryDisplayName,
    selectedSessionMarkerColor,
    selectedSessionTitle,
    selectedDirectoryPath,
    reply,
    transcript,
    systemPrompt,
    canSend,
    replyLoading,
    sttLoading,
    startNewSession,
    setDirectorySelectOpen,
    goDirectoryParent,
    goDirectoryRoot,
    selectCurrentDirectory,
    openDirectoryEntry,
    formatSessionUpdatedAt,
    refreshRegisteredDirectorySessions,
    loadSessionChildren,
    openSessionHistoryEntry,
    markSessionRead,
    markSelectedSessionUnread,
    reloadSelectedSession,
    resumeWaitingApprovalSession,
    renameSelectedDirectory,
    renameSelectedSessionTitle,
    selectSelectedSessionMarkerColor,
    removeSelectedDirectory,
    renameDirectoryForPath,
    renameSessionTitleForSession,
    selectSessionMarkerColorForSession,
    removeDirectoryForPath,
    markSessionUnread,
    showChatBottomToast,
    setTranscript,
    setSystemPrompt,
    sendReplyRequest,
    sendReplyTranscript,
    sendReplyRequestForPanelWithTranscript,
    sendReplyTranscriptForPanel,
    cancelReplyRequestForPanel,
    cancelCodexQueuedTurnForMessage,
    logSessionDiag,
  } = args;

  return useMemo(
    () => ({
      conversationMessages,
      llmSessionRestoreLoading,
      selectedSessionExecutionFact,
      selectedThreadStatusType,
      selectedSessionWaitingApproval,
      waitingApprovalResumeLoading,
      waitingApprovalResumeStatusText,
      directorySelectOpen,
      selectedDirectoryLabel,
      directoryExplorerPathLabel,
      directoryExplorerHasParent,
      directoryExplorerLoading,
      directoryExplorerError,
      directoryExplorerEntries,
      llmSessionRestoreError,
      registeredDirectories,
      directorySessionsById,
      sessionTitleOverridesById,
      sessionMarkerColorsById,
      selectedLlmSessionId,
      hasSelectedDirectory,
      selectedDirectoryDisplayName,
      selectedSessionMarkerColor,
      selectedSessionTitle,
      selectedDirectoryPath,
      reply,
      transcript,
      systemPrompt,
      canSend,
      replyLoading,
      sttLoading,
      startNewSession,
      setDirectorySelectOpen,
      goDirectoryParent,
      goDirectoryRoot,
      selectCurrentDirectory,
      openDirectoryEntry,
      formatSessionUpdatedAt,
      refreshRegisteredDirectorySessions,
      loadSessionChildren,
      openSessionHistoryEntry,
      markSessionRead,
      markSelectedSessionUnread,
      reloadSelectedSession,
      resumeWaitingApprovalSession,
      renameSelectedDirectory,
      renameSelectedSessionTitle,
      selectSelectedSessionMarkerColor,
      removeSelectedDirectory,
      renameDirectoryForPath,
      renameSessionTitleForSession,
      selectSessionMarkerColorForSession,
      removeDirectoryForPath,
      markSessionUnread,
      showChatBottomToast,
      setTranscript,
      setSystemPrompt,
      sendReplyRequest,
      sendReplyTranscript,
      sendReplyRequestForPanelWithTranscript,
      sendReplyTranscriptForPanel,
      cancelReplyRequestForPanel,
      cancelCodexQueuedTurnForMessage,
      logSessionDiag,
    }),
    [
      conversationMessages,
      llmSessionRestoreLoading,
      selectedSessionExecutionFact,
      selectedThreadStatusType,
      selectedSessionWaitingApproval,
      waitingApprovalResumeLoading,
      waitingApprovalResumeStatusText,
      directorySelectOpen,
      selectedDirectoryLabel,
      directoryExplorerPathLabel,
      directoryExplorerHasParent,
      directoryExplorerLoading,
      directoryExplorerError,
      directoryExplorerEntries,
      llmSessionRestoreError,
      registeredDirectories,
      directorySessionsById,
      sessionTitleOverridesById,
      sessionMarkerColorsById,
      selectedLlmSessionId,
      hasSelectedDirectory,
      selectedDirectoryDisplayName,
      selectedSessionMarkerColor,
      selectedSessionTitle,
      selectedDirectoryPath,
      reply,
      transcript,
      systemPrompt,
      canSend,
      replyLoading,
      sttLoading,
      startNewSession,
      setDirectorySelectOpen,
      goDirectoryParent,
      goDirectoryRoot,
      selectCurrentDirectory,
      openDirectoryEntry,
      formatSessionUpdatedAt,
      refreshRegisteredDirectorySessions,
      loadSessionChildren,
      openSessionHistoryEntry,
      markSessionRead,
      markSelectedSessionUnread,
      reloadSelectedSession,
      resumeWaitingApprovalSession,
      renameSelectedDirectory,
      renameSelectedSessionTitle,
      selectSelectedSessionMarkerColor,
      removeSelectedDirectory,
      renameDirectoryForPath,
      renameSessionTitleForSession,
      selectSessionMarkerColorForSession,
      removeDirectoryForPath,
      markSessionUnread,
      showChatBottomToast,
      setTranscript,
      setSystemPrompt,
      sendReplyRequest,
      sendReplyTranscript,
      sendReplyRequestForPanelWithTranscript,
      sendReplyTranscriptForPanel,
      cancelReplyRequestForPanel,
      cancelCodexQueuedTurnForMessage,
      logSessionDiag,
    ]
  );
}

export function useDebugRuntimeContextValue(
  args: DebugRuntimeContextValue
): DebugRuntimeContextValue {
  const {
    codexWsProbeLoading,
    probeCurrentWs,
    codexWsHandshakeProbeLoading,
    probeHandshakeOnly,
    codexWsDiagLoading,
    runWsDiag,
    runner8788SuiteLoading,
    runAuxServerSuite,
    codexWsE2eLoading,
    runWsE2e,
    codexWsHandshakeProbeStatus,
    codexWsDiagStatus,
    runner8788SuiteStatus,
    codexWsE2eStatus,
    llmRuntimeLimitsLoading,
    loadLlmRuntimeLimits,
    llmToolMaxRoundsInput,
    changeLlmToolMaxRoundsInput,
    llmToolMaxRoundsSaving,
    updateLlmToolMaxRounds,
    llmRuntimeLimits,
    llmRuntimeLimitsError,
    llmToolLogCompact,
    toggleLlmToolLogCompact,
  } = args;

  return useMemo(
    () => ({
      codexWsProbeLoading,
      probeCurrentWs,
      codexWsHandshakeProbeLoading,
      probeHandshakeOnly,
      codexWsDiagLoading,
      runWsDiag,
      runner8788SuiteLoading,
      runAuxServerSuite,
      codexWsE2eLoading,
      runWsE2e,
      codexWsHandshakeProbeStatus,
      codexWsDiagStatus,
      runner8788SuiteStatus,
      codexWsE2eStatus,
      llmRuntimeLimitsLoading,
      loadLlmRuntimeLimits,
      llmToolMaxRoundsInput,
      changeLlmToolMaxRoundsInput,
      llmToolMaxRoundsSaving,
      updateLlmToolMaxRounds,
      llmRuntimeLimits,
      llmRuntimeLimitsError,
      llmToolLogCompact,
      toggleLlmToolLogCompact,
    }),
    [
      codexWsProbeLoading,
      probeCurrentWs,
      codexWsHandshakeProbeLoading,
      probeHandshakeOnly,
      codexWsDiagLoading,
      runWsDiag,
      runner8788SuiteLoading,
      runAuxServerSuite,
      codexWsE2eLoading,
      runWsE2e,
      codexWsHandshakeProbeStatus,
      codexWsDiagStatus,
      runner8788SuiteStatus,
      codexWsE2eStatus,
      llmRuntimeLimitsLoading,
      loadLlmRuntimeLimits,
      llmToolMaxRoundsInput,
      changeLlmToolMaxRoundsInput,
      llmToolMaxRoundsSaving,
      updateLlmToolMaxRounds,
      llmRuntimeLimits,
      llmRuntimeLimitsError,
      llmToolLogCompact,
      toggleLlmToolLogCompact,
    ]
  );
}

type UseAudioLabContextValueArgs = Omit<AudioLabContextValue, "audioLabLogSendDisabled"> & {
  runnerUrl: string;
  runnerToken: string;
};

export function useAudioLabContextValue(args: UseAudioLabContextValueArgs): AudioLabContextValue {
  const {
    audioLabFlatlineDb,
    audioLabRunning,
    audioLabRecordingActive,
    audioLabPlaybackActive,
    audioLabInputName,
    audioLabAirPodsInput,
    audioLabElapsedMs,
    audioLabCallbackIntervalMs,
    audioLabLastDb,
    audioLabMinDb,
    audioLabMaxDb,
    audioLabFlatlineMs,
    audioLabPlaybackPositionMs,
    audioLabPlaybackStallMs,
    audioLabLoopCount,
    audioLabUnexpectedStopCount,
    audioLabPlaybackRecoverCount,
    audioLabLogQueuedCount,
    audioLabLogSentCount,
    audioLabLogStatus,
    audioLabRecentLogs,
    errorMessage,
    startProbe,
    stopProbe,
    startPlaybackOnly,
    stopPlaybackOnly,
    sendLogs,
    clearLogs,
    runnerUrl,
    runnerToken,
  } = args;

  return useMemo(
    () => ({
      audioLabFlatlineDb,
      audioLabRunning,
      audioLabRecordingActive,
      audioLabPlaybackActive,
      audioLabInputName,
      audioLabAirPodsInput,
      audioLabElapsedMs,
      audioLabCallbackIntervalMs,
      audioLabLastDb,
      audioLabMinDb,
      audioLabMaxDb,
      audioLabFlatlineMs,
      audioLabPlaybackPositionMs,
      audioLabPlaybackStallMs,
      audioLabLoopCount,
      audioLabUnexpectedStopCount,
      audioLabPlaybackRecoverCount,
      audioLabLogQueuedCount,
      audioLabLogSentCount,
      audioLabLogStatus,
      audioLabRecentLogs,
      audioLabLogSendDisabled: !runnerUrl.trim() || !runnerToken.trim() || audioLabLogQueuedCount <= 0,
      errorMessage,
      startProbe,
      stopProbe,
      startPlaybackOnly,
      stopPlaybackOnly,
      sendLogs,
      clearLogs,
    }),
    [
      audioLabFlatlineDb,
      audioLabRunning,
      audioLabRecordingActive,
      audioLabPlaybackActive,
      audioLabInputName,
      audioLabAirPodsInput,
      audioLabElapsedMs,
      audioLabCallbackIntervalMs,
      audioLabLastDb,
      audioLabMinDb,
      audioLabMaxDb,
      audioLabFlatlineMs,
      audioLabPlaybackPositionMs,
      audioLabPlaybackStallMs,
      audioLabLoopCount,
      audioLabUnexpectedStopCount,
      audioLabPlaybackRecoverCount,
      audioLabLogQueuedCount,
      audioLabLogSentCount,
      audioLabLogStatus,
      audioLabRecentLogs,
      runnerUrl,
      runnerToken,
      errorMessage,
      startProbe,
      stopProbe,
      startPlaybackOnly,
      stopPlaybackOnly,
      sendLogs,
      clearLogs,
    ]
  );
}

type UseChatDiagnosticsContextValueArgs = {
  codexCliStatusSnapshot: CodexCliStatusSnapshot | null;
  codexCliStatusFetchedAtMs: number;
  codexCliStatusLoading: boolean;
  codexAuthProfilesSnapshot: CodexAuthProfilesSnapshot | null;
  codexAuthProfilesLoading: boolean;
  codexAuthSwitching: boolean;
  codexAuthSwitchError: string;
  gitChangedFilesByDirectory: Record<string, GitChangedFilesDirectoryState>;
  refreshGitChangedFiles: (
    directory: string,
    options?: { force?: boolean },
  ) => Promise<void>;
  refreshCodexCliStatus: () => void;
  loadCodexAuthProfiles: () => void;
  switchCodexAuthProfile: (authId: string) => Promise<boolean>;
};

export function useChatDiagnosticsContextValue(
  args: UseChatDiagnosticsContextValueArgs
): ChatDiagnosticsContextValue {
  const {
    codexCliStatusSnapshot,
    codexCliStatusFetchedAtMs,
    codexCliStatusLoading,
    codexAuthProfilesSnapshot,
    codexAuthProfilesLoading,
    codexAuthSwitching,
    codexAuthSwitchError,
    gitChangedFilesByDirectory,
    refreshGitChangedFiles,
    refreshCodexCliStatus,
    loadCodexAuthProfiles,
    switchCodexAuthProfile,
  } = args;

  return useMemo(
    () => ({
      codexCliStatusText: codexCliStatusSnapshot?.statusText || "",
      codexCliStatusFetchedAtMs,
      codexCliStatusLoading,
      codexAuthProfileId: codexAuthProfilesSnapshot?.currentAuthId || "",
      codexAuthProfiles: codexAuthProfilesSnapshot?.profiles || [],
      codexAuthProfilesLoading,
      codexAuthSwitching,
      codexAuthSwitchError,
      gitChangedFilesByDirectory,
      refreshGitChangedFiles,
      refreshCodexCliStatus,
      loadCodexAuthProfiles,
      switchCodexAuthProfile,
    }),
    [
      codexCliStatusSnapshot,
      codexCliStatusFetchedAtMs,
      codexCliStatusLoading,
      codexAuthProfilesSnapshot,
      codexAuthProfilesLoading,
      codexAuthSwitching,
      codexAuthSwitchError,
      gitChangedFilesByDirectory,
      refreshGitChangedFiles,
      refreshCodexCliStatus,
      loadCodexAuthProfiles,
      switchCodexAuthProfile,
    ]
  );
}

export function useDebugConversationContextValue(
  args: DebugConversationContextValue
): DebugConversationContextValue {
  const {
    llmVisual,
    llmStatusText,
    llmUiStatusDetail,
    llmPixelIconKey,
    pixelStatusAnimations,
    llmActiveToolCalls,
    llmElapsedLabel,
    llmLastToolCall,
    streamAudioQueueSize,
    streamMode,
    streamLlmNativeDeltaCount,
    streamLlmPseudoDeltaCount,
    streamFirstNativeDeltaOffsetMs,
    ttsDebugStats,
    streamLlmProgress,
    streamLlmDeltas,
    streamSegments,
    trimForInline,
    replyDebug,
    latestAssistantYouTubeVideos,
    youtubePlayerMessageId,
    youtubePlayerVideoId,
    youtubeEmbedHtml,
    youtubePlayerSession,
    youtubeEmbedOrigin,
    onYouTubeWebViewMessage,
    onOpenLatestYouTubeVideo,
    formatYouTubePublishedDate,
    formatYouTubeViewCount,
    canReadReplyAudio,
    ttsLoading,
    synthesizeSpeech,
    hasTtsSound,
    stopTtsPlayback,
    ttsUri,
    history,
  } = args;

  return useMemo(
    () => ({
      llmVisual,
      llmStatusText,
      llmUiStatusDetail,
      llmPixelIconKey,
      pixelStatusAnimations,
      llmActiveToolCalls,
      llmElapsedLabel,
      llmLastToolCall,
      streamAudioQueueSize,
      streamMode,
      streamLlmNativeDeltaCount,
      streamLlmPseudoDeltaCount,
      streamFirstNativeDeltaOffsetMs,
      ttsDebugStats,
      streamLlmProgress,
      streamLlmDeltas,
      streamSegments,
      trimForInline,
      replyDebug,
      latestAssistantYouTubeVideos,
      youtubePlayerMessageId,
      youtubePlayerVideoId,
      youtubeEmbedHtml,
      youtubePlayerSession,
      youtubeEmbedOrigin,
      onYouTubeWebViewMessage,
      onOpenLatestYouTubeVideo,
      formatYouTubePublishedDate,
      formatYouTubeViewCount,
      canReadReplyAudio,
      ttsLoading,
      synthesizeSpeech,
      hasTtsSound,
      stopTtsPlayback,
      ttsUri,
      history,
    }),
    [
      llmVisual,
      llmStatusText,
      llmUiStatusDetail,
      llmPixelIconKey,
      pixelStatusAnimations,
      llmActiveToolCalls,
      llmElapsedLabel,
      llmLastToolCall,
      streamAudioQueueSize,
      streamMode,
      streamLlmNativeDeltaCount,
      streamLlmPseudoDeltaCount,
      streamFirstNativeDeltaOffsetMs,
      ttsDebugStats,
      streamLlmProgress,
      streamLlmDeltas,
      streamSegments,
      trimForInline,
      replyDebug,
      latestAssistantYouTubeVideos,
      youtubePlayerMessageId,
      youtubePlayerVideoId,
      youtubeEmbedHtml,
      youtubePlayerSession,
      youtubeEmbedOrigin,
      onYouTubeWebViewMessage,
      onOpenLatestYouTubeVideo,
      formatYouTubePublishedDate,
      formatYouTubeViewCount,
      canReadReplyAudio,
      ttsLoading,
      synthesizeSpeech,
      hasTtsSound,
      stopTtsPlayback,
      ttsUri,
      history,
    ]
  );
}

export function useDebugSpeechContextValue(
  args: DebugSpeechContextValue
): DebugSpeechContextValue {
  const {
    importSettingsJson,
    logSettingsJson,
    clearToolAutoApprovals,
    toolAutoApprovalRuleCount,
    isDirectNativeSttProvider,
    directNativeSttEnabled,
    directNativeSttActive,
    directNativeSttPreviewText,
    startDirectNativeStt,
    stopDirectNativeStt,
    autoRecordingEnabled,
    startAutoRecordingMode,
    stopAutoRecordingMode,
    autoWaveformAnimationEnabled,
    waveformDotGif,
    autoSpeechDetected,
    autoWaveformDebugOverlayEnabled,
    autoWaveformDebugText,
    autoRecordingState,
    autoMeteringDb,
    autoLastEvent,
    autoSegments,
    autoInputName,
    autoAirPodsInput,
    autoClientLogQueuedCount,
    autoClientLogSentCount,
    autoClientLogStatus,
    sendAutoClientLogs,
    clearAutoClientLogs,
    manualRecording,
    startRecording,
    stopRecording,
    recordingUri,
    transcribeRecording,
    recordingSec,
    clearRecordedClip,
  } = args;

  return useMemo(
    () => ({
      importSettingsJson,
      logSettingsJson,
      clearToolAutoApprovals,
      toolAutoApprovalRuleCount,
      isDirectNativeSttProvider,
      directNativeSttEnabled,
      directNativeSttActive,
      directNativeSttPreviewText,
      startDirectNativeStt,
      stopDirectNativeStt,
      autoRecordingEnabled,
      startAutoRecordingMode,
      stopAutoRecordingMode,
      autoWaveformAnimationEnabled,
      waveformDotGif,
      autoSpeechDetected,
      autoWaveformDebugOverlayEnabled,
      autoWaveformDebugText,
      autoRecordingState,
      autoMeteringDb,
      autoLastEvent,
      autoSegments,
      autoInputName,
      autoAirPodsInput,
      autoClientLogQueuedCount,
      autoClientLogSentCount,
      autoClientLogStatus,
      sendAutoClientLogs,
      clearAutoClientLogs,
      manualRecording,
      startRecording,
      stopRecording,
      recordingUri,
      transcribeRecording,
      recordingSec,
      clearRecordedClip,
    }),
    [
      importSettingsJson,
      logSettingsJson,
      clearToolAutoApprovals,
      toolAutoApprovalRuleCount,
      isDirectNativeSttProvider,
      directNativeSttEnabled,
      directNativeSttActive,
      directNativeSttPreviewText,
      startDirectNativeStt,
      stopDirectNativeStt,
      autoRecordingEnabled,
      startAutoRecordingMode,
      stopAutoRecordingMode,
      autoWaveformAnimationEnabled,
      waveformDotGif,
      autoSpeechDetected,
      autoWaveformDebugOverlayEnabled,
      autoWaveformDebugText,
      autoRecordingState,
      autoMeteringDb,
      autoLastEvent,
      autoSegments,
      autoInputName,
      autoAirPodsInput,
      autoClientLogQueuedCount,
      autoClientLogSentCount,
      autoClientLogStatus,
      sendAutoClientLogs,
      clearAutoClientLogs,
      manualRecording,
      startRecording,
      stopRecording,
      recordingUri,
      transcribeRecording,
      recordingSec,
      clearRecordedClip,
    ]
  );
}

export function useYouTubePlayerContextValue(
  args: YouTubePlayerContextValue
): YouTubePlayerContextValue {
  const {
    activeYouTubeQueuePositionLabel,
    youtubeVideoMetaById,
    conversationInlineAnchorMessageId,
    showFloatingYouTubePlayer,
    setYoutubeInlineAnchor,
    youtubePlayerVideoId,
    youtubeEmbedHtml,
    youtubeWebViewRef,
    youtubePlayerSession,
    youtubeEmbedOrigin,
    handleYouTubeWebViewMessage,
    openYouTubeVideo,
    formatYouTubePublishedDate,
    formatYouTubeViewCount,
    updateYouTubeInlineLayoutFromAnchor,
    streamReplyYouTubeVideos,
    youtubePlayerMessageId,
    streamReplyYouTubeVideoIds,
    showYouTubeOverlayPlayer,
    youtubeFloatingAnimatedPosition,
    markYouTubeFloatingControlInteraction,
    youtubeFloatingInteractionMode,
    youtubeFloatingPanResponder,
    closeYouTubePlayer,
  } = args;

  return useMemo(
    () => ({
      activeYouTubeQueuePositionLabel,
      youtubeVideoMetaById,
      conversationInlineAnchorMessageId,
      showFloatingYouTubePlayer,
      setYoutubeInlineAnchor,
      youtubePlayerVideoId,
      youtubeEmbedHtml,
      youtubeWebViewRef,
      youtubePlayerSession,
      youtubeEmbedOrigin,
      handleYouTubeWebViewMessage,
      openYouTubeVideo,
      formatYouTubePublishedDate,
      formatYouTubeViewCount,
      updateYouTubeInlineLayoutFromAnchor,
      streamReplyYouTubeVideos,
      youtubePlayerMessageId,
      streamReplyYouTubeVideoIds,
      showYouTubeOverlayPlayer,
      youtubeFloatingAnimatedPosition,
      markYouTubeFloatingControlInteraction,
      youtubeFloatingInteractionMode,
      youtubeFloatingPanResponder,
      closeYouTubePlayer,
    }),
    [
      activeYouTubeQueuePositionLabel,
      youtubeVideoMetaById,
      conversationInlineAnchorMessageId,
      showFloatingYouTubePlayer,
      setYoutubeInlineAnchor,
      youtubePlayerVideoId,
      youtubeEmbedHtml,
      youtubeWebViewRef,
      youtubePlayerSession,
      youtubeEmbedOrigin,
      handleYouTubeWebViewMessage,
      openYouTubeVideo,
      formatYouTubePublishedDate,
      formatYouTubeViewCount,
      updateYouTubeInlineLayoutFromAnchor,
      streamReplyYouTubeVideos,
      youtubePlayerMessageId,
      streamReplyYouTubeVideoIds,
      showYouTubeOverlayPlayer,
      youtubeFloatingAnimatedPosition,
      markYouTubeFloatingControlInteraction,
      youtubeFloatingInteractionMode,
      youtubeFloatingPanResponder,
      closeYouTubePlayer,
    ]
  );
}

export function useChatComposerContextValue(
  args: ChatComposerContextValue
): ChatComposerContextValue {
  const {
    composerWaveformVisible,
    autoWaveformAnimationEnabled,
    waveformDotGif,
    autoSpeechDetected,
    composerDirectSttVisible,
    directNativeSttPreviewText,
    chatComposerInputRef,
    showComposerFullscreenToggle,
    openComposerFullscreen,
    setComposerInputFocused,
    isDirectNativeSttProvider,
    directNativeSttEnabled,
    autoRecordingEnabled,
    manualRecording,
    faceTrackingEnabled,
    faceTrackingLooking,
    hasComposerText,
    canStopLlmTurn,
    stopDirectNativeStt,
    stopAutoRecordingMode,
    stopRecording,
    stopLlmTurn,
    startDirectNativeStt,
    startAutoRecordingMode,
    setFaceTrackingEnabledWithRef,
    faceTrackingRunning,
    setSlashCommandSelectOpen,
    slashCommandOptions,
    onSelectSlashCommand,
  } = args;

  return useMemo(
    () => ({
      composerWaveformVisible,
      autoWaveformAnimationEnabled,
      waveformDotGif,
      autoSpeechDetected,
      composerDirectSttVisible,
      directNativeSttPreviewText,
      chatComposerInputRef,
      showComposerFullscreenToggle,
      openComposerFullscreen,
      setComposerInputFocused,
      isDirectNativeSttProvider,
      directNativeSttEnabled,
      autoRecordingEnabled,
      manualRecording,
      faceTrackingEnabled,
      faceTrackingLooking,
      hasComposerText,
      canStopLlmTurn,
      stopDirectNativeStt,
      stopAutoRecordingMode,
      stopRecording,
      stopLlmTurn,
      startDirectNativeStt,
      startAutoRecordingMode,
      setFaceTrackingEnabledWithRef,
      faceTrackingRunning,
      setSlashCommandSelectOpen,
      slashCommandOptions,
      onSelectSlashCommand,
    }),
    [
      composerWaveformVisible,
      autoWaveformAnimationEnabled,
      waveformDotGif,
      autoSpeechDetected,
      composerDirectSttVisible,
      directNativeSttPreviewText,
      chatComposerInputRef,
      showComposerFullscreenToggle,
      openComposerFullscreen,
      setComposerInputFocused,
      isDirectNativeSttProvider,
      directNativeSttEnabled,
      autoRecordingEnabled,
      manualRecording,
      faceTrackingEnabled,
      faceTrackingLooking,
      hasComposerText,
      canStopLlmTurn,
      stopDirectNativeStt,
      stopAutoRecordingMode,
      stopRecording,
      stopLlmTurn,
      startDirectNativeStt,
      startAutoRecordingMode,
      setFaceTrackingEnabledWithRef,
      faceTrackingRunning,
      setSlashCommandSelectOpen,
      slashCommandOptions,
      onSelectSlashCommand,
    ]
  );
}

export function useChatVisualContextValue(
  args: ChatVisualContextValue
): ChatVisualContextValue {
  const {
    isRobotAnimating,
    pixelRobotImage,
    pixelRobotImageStatic,
    chatContextUsedPct,
    chatContextRingProgress,
    chatContextRingTrackColor,
    chatContextRingProgressColor,
    formatElapsedHhMmSs,
    llmStatusVisual,
    llmStatusLabel,
    resolvePixelStatusIconKey,
    buildSttMetaChips,
    ttsPlaybackMessageId,
    isTtsPlaybackActive,
    ttsSegmentProgress,
    pixelStatusAnimations,
    showChatThinkingPanel,
    chatThinkingCurrentMessage,
    llmElapsedLiveMs,
    chatThinkingLogLines,
    setChatThinkingLogExpanded,
    chatThinkingLogExpanded,
    isStreamWaveformPlaybackActive,
    stopWaveformPlayback,
    error,
    chatBottomToast,
    chatBottomToastAnimRef,
  } = args;

  return useMemo(
    () => ({
      isRobotAnimating,
      pixelRobotImage,
      pixelRobotImageStatic,
      chatContextUsedPct,
      chatContextRingProgress,
      chatContextRingTrackColor,
      chatContextRingProgressColor,
      formatElapsedHhMmSs,
      llmStatusVisual,
      llmStatusLabel,
      resolvePixelStatusIconKey,
      buildSttMetaChips,
      ttsPlaybackMessageId,
      isTtsPlaybackActive,
      ttsSegmentProgress,
      pixelStatusAnimations,
      showChatThinkingPanel,
      chatThinkingCurrentMessage,
      llmElapsedLiveMs,
      chatThinkingLogLines,
      setChatThinkingLogExpanded,
      chatThinkingLogExpanded,
      isStreamWaveformPlaybackActive,
      stopWaveformPlayback,
      error,
      chatBottomToast,
      chatBottomToastAnimRef,
    }),
    [
      isRobotAnimating,
      pixelRobotImage,
      pixelRobotImageStatic,
      chatContextUsedPct,
      chatContextRingProgress,
      chatContextRingTrackColor,
      chatContextRingProgressColor,
      formatElapsedHhMmSs,
      llmStatusVisual,
      llmStatusLabel,
      resolvePixelStatusIconKey,
      buildSttMetaChips,
      ttsPlaybackMessageId,
      isTtsPlaybackActive,
      ttsSegmentProgress,
      pixelStatusAnimations,
      showChatThinkingPanel,
      chatThinkingCurrentMessage,
      llmElapsedLiveMs,
      chatThinkingLogLines,
      setChatThinkingLogExpanded,
      chatThinkingLogExpanded,
      isStreamWaveformPlaybackActive,
      stopWaveformPlayback,
      error,
      chatBottomToast,
      chatBottomToastAnimRef,
    ]
  );
}

type UseChatScreenContextValueArgs = Omit<
  ChatScreenContextValue,
  "onChatTouchStart" | "onChatTouchEnd"
> & {
  handleChatTouchStart: () => void;
  handleChatTouchEnd: () => void;
};

export function useChatScreenContextValue(
  args: UseChatScreenContextValueArgs
): ChatScreenContextValue {
  const {
    approvalDialogPending,
    setChatScreenLayout,
    setChatViewportHeight,
    handleChatScroll,
    chatContentRef,
    handleChatTouchStart,
    handleChatTouchEnd,
    runnerUrl,
    runnerToken,
    runnerRouteSelection,
    isCodexCompactRunning,
    sanitizeTextForTts,
    handleAssistantAudioButtonPress,
  } = args;

  return useMemo(
    () => ({
      approvalDialogPending,
      setChatScreenLayout,
      setChatViewportHeight,
      handleChatScroll,
      chatContentRef,
      onChatTouchStart: handleChatTouchStart,
      onChatTouchEnd: handleChatTouchEnd,
      runnerUrl,
      runnerToken,
      runnerRouteSelection,
      isCodexCompactRunning,
      sanitizeTextForTts,
      handleAssistantAudioButtonPress,
    }),
    [
      approvalDialogPending,
      setChatScreenLayout,
      setChatViewportHeight,
      handleChatScroll,
      chatContentRef,
      handleChatTouchStart,
      handleChatTouchEnd,
      runnerUrl,
      runnerToken,
      runnerRouteSelection,
      isCodexCompactRunning,
      sanitizeTextForTts,
      handleAssistantAudioButtonPress,
    ]
  );
}
