import { useMemo } from "react";
import type { AppSettingsContextValue } from "../contexts/AppSettingsContext";
import type { AppShellContextValue } from "../contexts/AppShellContext";
import type { ChatComposerContextValue } from "../contexts/ChatComposerContext";
import type { ChatDiagnosticsContextValue } from "../contexts/ChatDiagnosticsContext";
import type { ChatScreenContextValue } from "../contexts/ChatScreenContext";
import type { ChatVisualContextValue } from "../contexts/ChatVisualContext";
import type { ConversationContextValue } from "../contexts/ConversationContext";
import type { YouTubePlayerContextValue } from "../contexts/YouTubePlayerContext";
import type {
  CodexAuthProfilesSnapshot,
  CodexCliStatusSnapshot,
  GitChangedFilesDirectoryState,
} from "../types/appTypes";

export function useAppShellContextValue(args: AppShellContextValue): AppShellContextValue {
  const {
    activeScreen,
    drawerOpen,
    setActiveScreen,
    setDrawerOpen,
    openDrawer,
    closeDrawer,
    openSettingsScreen,
    openSkiaBoardScreen,
    openCloudflareTunnelMonitorScreen,
  } = args;

  return useMemo(
    () => ({
      activeScreen,
      drawerOpen,
      setActiveScreen,
      setDrawerOpen,
      openDrawer,
      closeDrawer,
      openSettingsScreen,
      openSkiaBoardScreen,
      openCloudflareTunnelMonitorScreen,
    }),
    [activeScreen, drawerOpen, setActiveScreen, setDrawerOpen, openDrawer, closeDrawer, openSettingsScreen, openSkiaBoardScreen, openCloudflareTunnelMonitorScreen]
  );
}

export function useAppSettingsContextValue(args: AppSettingsContextValue): AppSettingsContextValue {
  const {
    runnerUrl,
    llmBackend,
    llmDirectory,
    runnerToken,
    cloudflareAccessClientId,
    cloudflareAccessEnabled,
    cloudflareRunnerUrl,
    localRunnerUrl,
    codexApprovalPolicy,
    selectedModelLabel,
    modelRef,
    reasoningEffort,
    modelOptions,
    thinkOptions,
    ttsProvider,
    sttProvider,
    voicesLoading,
    filteredVoices,
    ttsSpeedInput,
    ttsSpeed,
    voiceFilter,
    selectedVoiceId,
    recordingQualityPreset,
    autoTranscribeOnStop,
    autoReplyAfterStt,
    autoBargeInEnabled,
    autoSpeakerPriorityEnabled,
    autoSpeakAfterReply,
    faceIdRequiredForApproval,
    toolAutoApprovalRuleCount,
    changeRunnerUrl,
    changeLlmDirectory,
    changeRunnerToken,
    clearCloudflareAccessCredentials,
    applyCloudflareRunnerPairing,
    selectCodexApprovalPolicy,
    loadVoices,
    changeTtsSpeedInput,
    commitTtsSpeedInput,
    decreaseTtsSpeed,
    increaseTtsSpeed,
    changeVoiceFilter,
    selectVoiceId,
    selectTtsProvider,
    selectSttProvider,
    applyRecordingQualityPreset,
    toggleAutoTranscribeOnStop,
    toggleAutoReplyAfterStt,
    toggleAutoBargeInEnabled,
    toggleAutoSpeakerPriorityEnabled,
    toggleAutoSpeakAfterReply,
    toggleFaceIdRequiredForApproval,
    exportSettingsJson,
    importSettingsJson,
    clearToolAutoApprovals,
    openModelSelect,
    openThinkSelect,
    modelSelectOpen,
    thinkSelectOpen,
    setModelSelectOpen,
    setThinkSelectOpen,
    selectModel,
    selectThinkOption,
  } = args;

  return useMemo(
    () => ({
      runnerUrl,
      llmBackend,
      llmDirectory,
      runnerToken,
      cloudflareAccessClientId,
      cloudflareAccessEnabled,
      cloudflareRunnerUrl,
      localRunnerUrl,
      codexApprovalPolicy,
      selectedModelLabel,
      modelRef,
      reasoningEffort,
      modelOptions,
      thinkOptions,
      ttsProvider,
      sttProvider,
      voicesLoading,
      filteredVoices,
      ttsSpeedInput,
      ttsSpeed,
      voiceFilter,
      selectedVoiceId,
      recordingQualityPreset,
      autoTranscribeOnStop,
      autoReplyAfterStt,
      autoBargeInEnabled,
      autoSpeakerPriorityEnabled,
      autoSpeakAfterReply,
      faceIdRequiredForApproval,
      toolAutoApprovalRuleCount,
      changeRunnerUrl,
      changeLlmDirectory,
      changeRunnerToken,
      clearCloudflareAccessCredentials,
      applyCloudflareRunnerPairing,
      selectCodexApprovalPolicy,
      loadVoices,
      changeTtsSpeedInput,
      commitTtsSpeedInput,
      decreaseTtsSpeed,
      increaseTtsSpeed,
      changeVoiceFilter,
      selectVoiceId,
      selectTtsProvider,
      selectSttProvider,
      applyRecordingQualityPreset,
      toggleAutoTranscribeOnStop,
      toggleAutoReplyAfterStt,
      toggleAutoBargeInEnabled,
      toggleAutoSpeakerPriorityEnabled,
      toggleAutoSpeakAfterReply,
      toggleFaceIdRequiredForApproval,
      exportSettingsJson,
      importSettingsJson,
      clearToolAutoApprovals,
      openModelSelect,
      openThinkSelect,
      modelSelectOpen,
      thinkSelectOpen,
      setModelSelectOpen,
      setThinkSelectOpen,
      selectModel,
      selectThinkOption,
    }),
    [
      runnerUrl,
      llmBackend,
      llmDirectory,
      runnerToken,
      cloudflareAccessClientId,
      cloudflareAccessEnabled,
      cloudflareRunnerUrl,
      localRunnerUrl,
      codexApprovalPolicy,
      selectedModelLabel,
      modelRef,
      reasoningEffort,
      modelOptions,
      thinkOptions,
      ttsProvider,
      sttProvider,
      voicesLoading,
      filteredVoices,
      ttsSpeedInput,
      ttsSpeed,
      voiceFilter,
      selectedVoiceId,
      recordingQualityPreset,
      autoTranscribeOnStop,
      autoReplyAfterStt,
      autoBargeInEnabled,
      autoSpeakerPriorityEnabled,
      autoSpeakAfterReply,
      faceIdRequiredForApproval,
      toolAutoApprovalRuleCount,
      changeRunnerUrl,
      changeLlmDirectory,
      changeRunnerToken,
      clearCloudflareAccessCredentials,
      applyCloudflareRunnerPairing,
      selectCodexApprovalPolicy,
      loadVoices,
      changeTtsSpeedInput,
      commitTtsSpeedInput,
      decreaseTtsSpeed,
      increaseTtsSpeed,
      changeVoiceFilter,
      selectVoiceId,
      selectTtsProvider,
      selectSttProvider,
      applyRecordingQualityPreset,
      toggleAutoTranscribeOnStop,
      toggleAutoReplyAfterStt,
      toggleAutoBargeInEnabled,
      toggleAutoSpeakerPriorityEnabled,
      toggleAutoSpeakAfterReply,
      toggleFaceIdRequiredForApproval,
      exportSettingsJson,
      importSettingsJson,
      clearToolAutoApprovals,
      openModelSelect,
      openThinkSelect,
      modelSelectOpen,
      thinkSelectOpen,
      setModelSelectOpen,
      setThinkSelectOpen,
      selectModel,
      selectThinkOption,
    ]
  );
}

export function useConversationContextValue(
  args: ConversationContextValue
): ConversationContextValue {
  const {
    conversationMessages,
    llmSessionRestoreLoading,
    selectedSessionExecutionFact,
    selectedThreadStatusType,
    selectedSessionWaitingApproval,
    waitingApprovalResumeLoading,
    waitingApprovalResumeStatusText,
    directorySelectOpen,
    selectedDirectoryLabel,
    directoryExplorerPathLabel,
    directoryExplorerHasParent,
    directoryExplorerLoading,
    directoryExplorerError,
    directoryExplorerEntries,
    llmSessionRestoreError,
    registeredDirectories,
    directorySessionsById,
    directorySessionSync,
    sessionTitleOverridesById,
    sessionMarkerColorsById,
    selectedLlmSessionId,
    hasSelectedDirectory,
    selectedDirectoryDisplayName,
    selectedSessionMarkerColor,
    selectedSessionTitle,
    selectedDirectoryPath,
    reply,
    transcript,
    systemPrompt,
    canSend,
    replyLoading,
    sttLoading,
    startNewSession,
    setDirectorySelectOpen,
    goDirectoryParent,
    goDirectoryRoot,
    selectCurrentDirectory,
    openDirectoryEntry,
    formatSessionUpdatedAt,
    ensureRegisteredDirectorySessions,
    refreshRegisteredDirectorySessions,
    loadSessionChildren,
    loadSessionChildrenBatch,
    openSessionHistoryEntry,
    markSessionRead,
    markSelectedSessionUnread,
    reloadSelectedSession,
    resumeWaitingApprovalSession,
    renameSelectedDirectory,
    renameSelectedSessionTitle,
    selectSelectedSessionMarkerColor,
    removeSelectedDirectory,
    renameDirectoryForPath,
    renameSessionTitleForSession,
    selectSessionMarkerColorForSession,
    removeDirectoryForPath,
    markSessionUnread,
    showChatBottomToast,
    setTranscript,
    setSystemPrompt,
    sendReplyRequest,
    sendReplyTranscript,
    sendReplyRequestForPanelWithTranscript,
    sendReplyTranscriptForPanel,
    cancelReplyRequestForPanel,
    cancelCodexQueuedTurnForMessage,
    logSessionDiag,
  } = args;

  return useMemo(
    () => ({
      conversationMessages,
      llmSessionRestoreLoading,
      selectedSessionExecutionFact,
      selectedThreadStatusType,
      selectedSessionWaitingApproval,
      waitingApprovalResumeLoading,
      waitingApprovalResumeStatusText,
      directorySelectOpen,
      selectedDirectoryLabel,
      directoryExplorerPathLabel,
      directoryExplorerHasParent,
      directoryExplorerLoading,
      directoryExplorerError,
      directoryExplorerEntries,
      llmSessionRestoreError,
      registeredDirectories,
      directorySessionsById,
      directorySessionSync,
      sessionTitleOverridesById,
      sessionMarkerColorsById,
      selectedLlmSessionId,
      hasSelectedDirectory,
      selectedDirectoryDisplayName,
      selectedSessionMarkerColor,
      selectedSessionTitle,
      selectedDirectoryPath,
      reply,
      transcript,
      systemPrompt,
      canSend,
      replyLoading,
      sttLoading,
      startNewSession,
      setDirectorySelectOpen,
      goDirectoryParent,
      goDirectoryRoot,
      selectCurrentDirectory,
      openDirectoryEntry,
      formatSessionUpdatedAt,
      ensureRegisteredDirectorySessions,
      refreshRegisteredDirectorySessions,
      loadSessionChildren,
      loadSessionChildrenBatch,
      openSessionHistoryEntry,
      markSessionRead,
      markSelectedSessionUnread,
      reloadSelectedSession,
      resumeWaitingApprovalSession,
      renameSelectedDirectory,
      renameSelectedSessionTitle,
      selectSelectedSessionMarkerColor,
      removeSelectedDirectory,
      renameDirectoryForPath,
      renameSessionTitleForSession,
      selectSessionMarkerColorForSession,
      removeDirectoryForPath,
      markSessionUnread,
      showChatBottomToast,
      setTranscript,
      setSystemPrompt,
      sendReplyRequest,
      sendReplyTranscript,
      sendReplyRequestForPanelWithTranscript,
      sendReplyTranscriptForPanel,
      cancelReplyRequestForPanel,
      cancelCodexQueuedTurnForMessage,
      logSessionDiag,
    }),
    [
      conversationMessages,
      llmSessionRestoreLoading,
      selectedSessionExecutionFact,
      selectedThreadStatusType,
      selectedSessionWaitingApproval,
      waitingApprovalResumeLoading,
      waitingApprovalResumeStatusText,
      directorySelectOpen,
      selectedDirectoryLabel,
      directoryExplorerPathLabel,
      directoryExplorerHasParent,
      directoryExplorerLoading,
      directoryExplorerError,
      directoryExplorerEntries,
      llmSessionRestoreError,
      registeredDirectories,
      directorySessionsById,
      directorySessionSync,
      sessionTitleOverridesById,
      sessionMarkerColorsById,
      selectedLlmSessionId,
      hasSelectedDirectory,
      selectedDirectoryDisplayName,
      selectedSessionMarkerColor,
      selectedSessionTitle,
      selectedDirectoryPath,
      reply,
      transcript,
      systemPrompt,
      canSend,
      replyLoading,
      sttLoading,
      startNewSession,
      setDirectorySelectOpen,
      goDirectoryParent,
      goDirectoryRoot,
      selectCurrentDirectory,
      openDirectoryEntry,
      formatSessionUpdatedAt,
      ensureRegisteredDirectorySessions,
      refreshRegisteredDirectorySessions,
      loadSessionChildren,
      loadSessionChildrenBatch,
      openSessionHistoryEntry,
      markSessionRead,
      markSelectedSessionUnread,
      reloadSelectedSession,
      resumeWaitingApprovalSession,
      renameSelectedDirectory,
      renameSelectedSessionTitle,
      selectSelectedSessionMarkerColor,
      removeSelectedDirectory,
      renameDirectoryForPath,
      renameSessionTitleForSession,
      selectSessionMarkerColorForSession,
      removeDirectoryForPath,
      markSessionUnread,
      showChatBottomToast,
      setTranscript,
      setSystemPrompt,
      sendReplyRequest,
      sendReplyTranscript,
      sendReplyRequestForPanelWithTranscript,
      sendReplyTranscriptForPanel,
      cancelReplyRequestForPanel,
      cancelCodexQueuedTurnForMessage,
      logSessionDiag,
    ]
  );
}

type UseChatDiagnosticsContextValueArgs = {
  codexCliStatusSnapshot: CodexCliStatusSnapshot | null;
  codexCliStatusFetchedAtMs: number;
  codexCliStatusLoading: boolean;
  codexAuthProfilesSnapshot: CodexAuthProfilesSnapshot | null;
  codexAuthProfilesLoading: boolean;
  codexAuthSwitching: boolean;
  codexAuthSwitchError: string;
  gitChangedFilesByDirectory: Record<string, GitChangedFilesDirectoryState>;
  refreshGitChangedFiles: (
    directory: string,
    options?: { force?: boolean },
  ) => Promise<void>;
  refreshCodexCliStatus: () => void;
  loadCodexAuthProfiles: () => void;
  switchCodexAuthProfile: (authId: string) => Promise<boolean>;
};

export function useChatDiagnosticsContextValue(
  args: UseChatDiagnosticsContextValueArgs
): ChatDiagnosticsContextValue {
  const {
    codexCliStatusSnapshot,
    codexCliStatusFetchedAtMs,
    codexCliStatusLoading,
    codexAuthProfilesSnapshot,
    codexAuthProfilesLoading,
    codexAuthSwitching,
    codexAuthSwitchError,
    gitChangedFilesByDirectory,
    refreshGitChangedFiles,
    refreshCodexCliStatus,
    loadCodexAuthProfiles,
    switchCodexAuthProfile,
  } = args;

  return useMemo(
    () => ({
      codexCliStatusText: codexCliStatusSnapshot?.statusText || "",
      codexCliStatusFetchedAtMs,
      codexCliStatusLoading,
      codexAuthProfileId: codexAuthProfilesSnapshot?.currentAuthId || "",
      codexAuthProfiles: codexAuthProfilesSnapshot?.profiles || [],
      codexAuthProfilesLoading,
      codexAuthSwitching,
      codexAuthSwitchError,
      gitChangedFilesByDirectory,
      refreshGitChangedFiles,
      refreshCodexCliStatus,
      loadCodexAuthProfiles,
      switchCodexAuthProfile,
    }),
    [
      codexCliStatusSnapshot,
      codexCliStatusFetchedAtMs,
      codexCliStatusLoading,
      codexAuthProfilesSnapshot,
      codexAuthProfilesLoading,
      codexAuthSwitching,
      codexAuthSwitchError,
      gitChangedFilesByDirectory,
      refreshGitChangedFiles,
      refreshCodexCliStatus,
      loadCodexAuthProfiles,
      switchCodexAuthProfile,
    ]
  );
}

export function useYouTubePlayerContextValue(
  args: YouTubePlayerContextValue
): YouTubePlayerContextValue {
  const {
    activeYouTubeQueuePositionLabel,
    youtubeVideoMetaById,
    conversationInlineAnchorMessageId,
    showFloatingYouTubePlayer,
    setYoutubeInlineAnchor,
    youtubePlayerVideoId,
    youtubeEmbedHtml,
    youtubeWebViewRef,
    youtubePlayerSession,
    youtubeEmbedOrigin,
    handleYouTubeWebViewMessage,
    openYouTubeVideo,
    formatYouTubePublishedDate,
    formatYouTubeViewCount,
    updateYouTubeInlineLayoutFromAnchor,
    streamReplyYouTubeVideos,
    youtubePlayerMessageId,
    streamReplyYouTubeVideoIds,
    showYouTubeOverlayPlayer,
    youtubeFloatingAnimatedPosition,
    markYouTubeFloatingControlInteraction,
    youtubeFloatingInteractionMode,
    youtubeFloatingPanResponder,
    closeYouTubePlayer,
  } = args;

  return useMemo(
    () => ({
      activeYouTubeQueuePositionLabel,
      youtubeVideoMetaById,
      conversationInlineAnchorMessageId,
      showFloatingYouTubePlayer,
      setYoutubeInlineAnchor,
      youtubePlayerVideoId,
      youtubeEmbedHtml,
      youtubeWebViewRef,
      youtubePlayerSession,
      youtubeEmbedOrigin,
      handleYouTubeWebViewMessage,
      openYouTubeVideo,
      formatYouTubePublishedDate,
      formatYouTubeViewCount,
      updateYouTubeInlineLayoutFromAnchor,
      streamReplyYouTubeVideos,
      youtubePlayerMessageId,
      streamReplyYouTubeVideoIds,
      showYouTubeOverlayPlayer,
      youtubeFloatingAnimatedPosition,
      markYouTubeFloatingControlInteraction,
      youtubeFloatingInteractionMode,
      youtubeFloatingPanResponder,
      closeYouTubePlayer,
    }),
    [
      activeYouTubeQueuePositionLabel,
      youtubeVideoMetaById,
      conversationInlineAnchorMessageId,
      showFloatingYouTubePlayer,
      setYoutubeInlineAnchor,
      youtubePlayerVideoId,
      youtubeEmbedHtml,
      youtubeWebViewRef,
      youtubePlayerSession,
      youtubeEmbedOrigin,
      handleYouTubeWebViewMessage,
      openYouTubeVideo,
      formatYouTubePublishedDate,
      formatYouTubeViewCount,
      updateYouTubeInlineLayoutFromAnchor,
      streamReplyYouTubeVideos,
      youtubePlayerMessageId,
      streamReplyYouTubeVideoIds,
      showYouTubeOverlayPlayer,
      youtubeFloatingAnimatedPosition,
      markYouTubeFloatingControlInteraction,
      youtubeFloatingInteractionMode,
      youtubeFloatingPanResponder,
      closeYouTubePlayer,
    ]
  );
}

export function useChatComposerContextValue(
  args: ChatComposerContextValue
): ChatComposerContextValue {
  const {
    composerWaveformVisible,
    autoWaveformAnimationEnabled,
    waveformDotGif,
    autoSpeechDetected,
    composerDirectSttVisible,
    directNativeSttPreviewText,
    chatComposerInputRef,
    showComposerFullscreenToggle,
    openComposerFullscreen,
    setComposerInputFocused,
    isDirectNativeSttProvider,
    directNativeSttEnabled,
    autoRecordingEnabled,
    manualRecording,
    faceTrackingEnabled,
    faceTrackingLooking,
    hasComposerText,
    canStopLlmTurn,
    stopDirectNativeStt,
    stopAutoRecordingMode,
    stopRecording,
    stopLlmTurn,
    startDirectNativeStt,
    startAutoRecordingMode,
    setFaceTrackingEnabledWithRef,
    faceTrackingRunning,
    setSlashCommandSelectOpen,
    slashCommandOptions,
    onSelectSlashCommand,
  } = args;

  return useMemo(
    () => ({
      composerWaveformVisible,
      autoWaveformAnimationEnabled,
      waveformDotGif,
      autoSpeechDetected,
      composerDirectSttVisible,
      directNativeSttPreviewText,
      chatComposerInputRef,
      showComposerFullscreenToggle,
      openComposerFullscreen,
      setComposerInputFocused,
      isDirectNativeSttProvider,
      directNativeSttEnabled,
      autoRecordingEnabled,
      manualRecording,
      faceTrackingEnabled,
      faceTrackingLooking,
      hasComposerText,
      canStopLlmTurn,
      stopDirectNativeStt,
      stopAutoRecordingMode,
      stopRecording,
      stopLlmTurn,
      startDirectNativeStt,
      startAutoRecordingMode,
      setFaceTrackingEnabledWithRef,
      faceTrackingRunning,
      setSlashCommandSelectOpen,
      slashCommandOptions,
      onSelectSlashCommand,
    }),
    [
      composerWaveformVisible,
      autoWaveformAnimationEnabled,
      waveformDotGif,
      autoSpeechDetected,
      composerDirectSttVisible,
      directNativeSttPreviewText,
      chatComposerInputRef,
      showComposerFullscreenToggle,
      openComposerFullscreen,
      setComposerInputFocused,
      isDirectNativeSttProvider,
      directNativeSttEnabled,
      autoRecordingEnabled,
      manualRecording,
      faceTrackingEnabled,
      faceTrackingLooking,
      hasComposerText,
      canStopLlmTurn,
      stopDirectNativeStt,
      stopAutoRecordingMode,
      stopRecording,
      stopLlmTurn,
      startDirectNativeStt,
      startAutoRecordingMode,
      setFaceTrackingEnabledWithRef,
      faceTrackingRunning,
      setSlashCommandSelectOpen,
      slashCommandOptions,
      onSelectSlashCommand,
    ]
  );
}

export function useChatVisualContextValue(
  args: ChatVisualContextValue
): ChatVisualContextValue {
  const {
    isRobotAnimating,
    pixelRobotImage,
    pixelRobotImageStatic,
    chatContextUsedPct,
    chatContextRingProgress,
    chatContextRingTrackColor,
    chatContextRingProgressColor,
    formatElapsedHhMmSs,
    llmStatusVisual,
    llmStatusLabel,
    resolvePixelStatusIconKey,
    buildSttMetaChips,
    ttsPlaybackMessageId,
    isTtsPlaybackActive,
    ttsSegmentProgress,
    pixelStatusAnimations,
    showChatThinkingPanel,
    chatThinkingCurrentMessage,
    llmElapsedLiveMs,
    chatThinkingLogLines,
    setChatThinkingLogExpanded,
    chatThinkingLogExpanded,
    stopWaveformPlayback,
    error,
    chatBottomToast,
    chatBottomToastAnimRef,
  } = args;

  return useMemo(
    () => ({
      isRobotAnimating,
      pixelRobotImage,
      pixelRobotImageStatic,
      chatContextUsedPct,
      chatContextRingProgress,
      chatContextRingTrackColor,
      chatContextRingProgressColor,
      formatElapsedHhMmSs,
      llmStatusVisual,
      llmStatusLabel,
      resolvePixelStatusIconKey,
      buildSttMetaChips,
      ttsPlaybackMessageId,
      isTtsPlaybackActive,
      ttsSegmentProgress,
      pixelStatusAnimations,
      showChatThinkingPanel,
      chatThinkingCurrentMessage,
      llmElapsedLiveMs,
      chatThinkingLogLines,
      setChatThinkingLogExpanded,
      chatThinkingLogExpanded,
      stopWaveformPlayback,
      error,
      chatBottomToast,
      chatBottomToastAnimRef,
    }),
    [
      isRobotAnimating,
      pixelRobotImage,
      pixelRobotImageStatic,
      chatContextUsedPct,
      chatContextRingProgress,
      chatContextRingTrackColor,
      chatContextRingProgressColor,
      formatElapsedHhMmSs,
      llmStatusVisual,
      llmStatusLabel,
      resolvePixelStatusIconKey,
      buildSttMetaChips,
      ttsPlaybackMessageId,
      isTtsPlaybackActive,
      ttsSegmentProgress,
      pixelStatusAnimations,
      showChatThinkingPanel,
      chatThinkingCurrentMessage,
      llmElapsedLiveMs,
      chatThinkingLogLines,
      setChatThinkingLogExpanded,
      chatThinkingLogExpanded,
      stopWaveformPlayback,
      error,
      chatBottomToast,
      chatBottomToastAnimRef,
    ]
  );
}

type UseChatScreenContextValueArgs = Omit<
  ChatScreenContextValue,
  "onChatTouchStart" | "onChatTouchEnd"
> & {
  handleChatTouchStart: () => void;
  handleChatTouchEnd: () => void;
};

export function useChatScreenContextValue(
  args: UseChatScreenContextValueArgs
): ChatScreenContextValue {
  const {
    approvalDialogPending,
    setChatScreenLayout,
    setChatViewportHeight,
    handleChatScroll,
    chatContentRef,
    handleChatTouchStart,
    handleChatTouchEnd,
    runnerUrl,
    runnerToken,
    runnerRouteSelection,
    isCodexCompactRunning,
    sanitizeTextForTts,
    handleAssistantAudioButtonPress,
    sessionHistoryPagingById,
    loadOlderSessionHistory,
  } = args;

  return useMemo(
    () => ({
      approvalDialogPending,
      setChatScreenLayout,
      setChatViewportHeight,
      handleChatScroll,
      chatContentRef,
      onChatTouchStart: handleChatTouchStart,
      onChatTouchEnd: handleChatTouchEnd,
      runnerUrl,
      runnerToken,
      runnerRouteSelection,
      isCodexCompactRunning,
      sanitizeTextForTts,
      handleAssistantAudioButtonPress,
      sessionHistoryPagingById,
      loadOlderSessionHistory,
    }),
    [
      approvalDialogPending,
      setChatScreenLayout,
      setChatViewportHeight,
      handleChatScroll,
      chatContentRef,
      handleChatTouchStart,
      handleChatTouchEnd,
      runnerUrl,
      runnerToken,
      runnerRouteSelection,
      isCodexCompactRunning,
      sanitizeTextForTts,
      handleAssistantAudioButtonPress,
      sessionHistoryPagingById,
      loadOlderSessionHistory,
    ]
  );
}
